### ISSUE TITLE
Conda Installation of the dataprep AI is not supported

### ISSUE THREAD

**Issue by abhisheksundarraman** [sfu-db/dataprep#103]
Conda Installation for the data prep AI is not supported.

$ conda install dataprep
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - dataprep

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by dovahcrow** [comment]
Currently, you can install our package through PyPI using command `pip install dataprep`. installation using conda will be supported in the future.

**Comment by jnwang** [comment]
This seems an easy but important task to do. Shall we prioritize it?

https://conda-forge.org/#add_recipe

**Comment by twsl** [comment]
I'd love to see this implemented. Any way I can help?

**Comment by jnwang** [comment]
Thanks @twsl for offering your help. Would like to work on this issue and let us know how long it will take it?

**Comment by twsl** [comment]
who should I name as recipe maintainers? I'm not sure, if I'll be able to maintain it in the future myself.

**Comment by dovahcrow** [comment]
@twsl I think you can add me "Weiyuan Wu <youngw@sfu.ca>" into the maintainers list.

**Comment by dovahcrow** [comment]
I uploaded DataPrep to conda repo [`sfu-db`](https://anaconda.org/SFU-DB/repo). I think you can install it through `conda install -c sfu-db dataprep` now.

However, this build is only for Linux. I haven't figure out how to crossbuild the package for Windows and MacOS.

**Comment by twsl** [comment]
nice to see, that you already pushed this. I was fiddling around with cross plattform builds

**Comment by dovahcrow** [comment]
@twsl Thanks! I just figured out by replacing one of DataPrep's dependency we can make it a noarch package. Hopefully next release 0.2.10 (next week) we will have DataPrep appear on conda-forge channel.

**Comment by abhisheksundarraman** [comment]
This is great news for the Data-prep AI and all of its users thanks to the
team for putting all this together.

I am sure people would now find it easier to install and use this feature
and that was the whole purpose of this change request to enable it on conda.

Thanks a lot once again !!

Cheers,
Abhishek S
Big Data Master's Student
Simon Fraser University, Burnaby, BC.

**Comment by twsl** [comment]
@dovahcrow is dataprep now noarch? should I push my current progress to conda forge or do you want to finish this?

**Comment by dovahcrow** [comment]
@twsl Yep DataPrep is now noarch. Although we successfully submitted the recipe to conda-forge, we met a problem for building it successfully. May I ask if you can submit your PR to https://github.com/conda-forge/dataprep-feedstock?

**Comment by dovahcrow** [comment]
Dataprep is now officially on conda-forge! https://anaconda.org/conda-forge/dataprep
