### ISSUE TITLE
No module named 'toml'

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#115]
I tried to upgrade dataprep to the latest version: **pip install -U dataprep**, but got the following error:

<img width="761" alt="Screen Shot 2020-03-29 at 9 07 11 PM" src="https://user-images.githubusercontent.com/1028970/77874377-97785180-7201-11ea-8650-7e5833061cb8.png">

**Comment by dovahcrow** [comment]
It's a known issue and will be fixed in the next release. Currently, you can run `pip install toml` to circumvent.

**Comment by jnwang** [comment]
Thanks!
