### ISSUE TITLE
eda.plot_missing: error when passing column

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#120]
I'm getting this error when running the following code
```python
import pandas as pd
df = pd.read_csv("https://s3-us-west-2.amazonaws.com/dataprep.dsl/datasets/suicide-rate.csv")
plot_missing(df, "suicides")
```
![Screen Shot 2020-04-02 at 12 26 49 PM](https://user-images.githubusercontent.com/25874021/78293328-47d5a680-74dd-11ea-8c0d-e5c56f642470.png)
@Waterpine @jinglinpeng is anyone else getting this error?  I'm using dask version 2.9.1

**Comment by jinglinpeng** [comment]
It works in my environment. I'm using dask 2.9.0.

**Comment by brandonlockhart** [comment]
Thanks @jinglinpeng, it works for me with dask 2.9.0 but I get an error with dask 2.9.1

**Comment by dovahcrow** [comment]
Ok I'm gonna update the dependencies.
