### ISSUE TITLE
dataprep.eda: plot(df,x,y) with categorical variables bar chart problems

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#123]
Some labels are overlapping in the nested bar chart:
![Screen Shot 2020-04-04 at 9 21 45 AM](https://user-images.githubusercontent.com/25874021/78455931-cbb29e80-7655-11ea-9159-32e7fef22b80.png)

I think we should include the count in the tooltip of the stacked bar chart since this plot could be deceiving if there is a small number of observations in a group
![Screen Shot 2020-04-04 at 9 23 36 AM](https://user-images.githubusercontent.com/25874021/78455966-03214b00-7656-11ea-8d1e-f762cefca0a3.png)

**Comment by dovahcrow** [comment]
@brandonlockhart Are these bars cumulative or overlapping?
