### ISSUE TITLE
fix KDE plot

### ISSUE THREAD

**Issue by liuyejia** [sfu-db/dataprep#127]
The KDE plot of Dataprep is bad and needs to be fixed:
<img width="502" alt="Screen Shot 2020-04-10 at 4 59 35 PM" src="https://user-images.githubusercontent.com/10182591/79030226-e2249280-7b4c-11ea-99bc-94b52f9a12ac.png">

**Comment by liuyejia** [comment]
The approximation of KDE to the histogram is not correct.

**Comment by jinglinpeng** [comment]
@liuyejia Hi, Yejia. Could you please paste the code that generates the fig.?
