### ISSUE TITLE
support of time series

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#129]
This issue is about the rough idea to support time series in _dataprep.eda_. 

Essentially, datatime could be regarded as a numeric type, and it could be transformed to timestamp (float) via _datatime.timestamp()_ or _pd.to_numeric()_. Hence, we could do the following work as the initial support of time series.

1. Identify the column with _datatime64_ type in the dataframe. 
2. plot(df) & plot(df, x): handle time series column like numeric column, which could be binalized. When show the ticks of time series column, show the datetime string via function like _datatime.strftime()_.  An example output is [https://pandas.pydata.org/pandas-docs/version/0.13/visualization.html](https://pandas.pydata.org/pandas-docs/version/0.13/visualization.html)  
3. plot(df, x, y): When x is a datetime column and y is a numeric column, change the scatter plot with the line chart, which shows how y changes with x. For all other cases, apply the processing as step 2.
4. plot_correlation: we could ignore the datetime column as pandas does, or transform datetime to numeric column via _pd.to_numeric()_ and then apply the original processing.
5. plot_missing: apply the similar processing of step 2.

**Comment by jnwang** [comment]
It looks like a quick fix. One question about this design. Do you need to add Step 1 to every function, plot, plot_correlation, plot_missing? The code could look redundant.

**Comment by dovahcrow** [comment]
@jnwang The type detection code can be put into `dtypes.py` for reuse.
@jinglinpeng There're two datetime types `pd.DatetimeTZDtype` and `np.datetime64`. I already listed them in `dtypes.py`.

**Comment by brandonlockhart** [comment]
I have two thoughts:
1. For plot(df, *) we currently bin by creating equal length intervals between the minimum and maximum value in a column, but I think the bin endpoints are very important for time series. I wonder if we should add a parameter like `timebin` where  for example `timebin="month"` we would bin by year and month. This would be straightforward with a _datetime_ column type as was proposed.
2. For plot(df,x,y), if I understand correctly, the line chart would only work if there is one y value for every time point. Maybe we should aggregate over the y values by bins in x and show the aggregates in a line chart. But aggregation is something we should think about irrespective of datetime columns.

**Comment by jinglinpeng** [comment]
@brandonlockhart  I totally agree with the second idea. For this implementation, we could keep more points, like 1000,  to make the line chart (but we could show only 10 ticks in x-axis).  For the first idea, if we bin by year and month, it looks hard to control the number of displayed bins, as the time range could be very large.

**Comment by brandonlockhart** [comment]
@jinglinpeng Above I'm talking about the bin endpoints, not ticks. To give an example, suppose we have a dataset with a time column with values from November 4, 2019 to April 11, 2020. If we handle this as a numeric column and build a histogram, we would have bins like [Nov 4,Nov 29), [Nov 29, Dec, 22),.... In my opinion, it would be good for us to support the bins November, December, ..., April, ie using natural time intervals. My idea was to define the bin endpoints the same way as for a numeric column by default, and to give the user a parameter to specify the bins, eg "year", "month", "day". But perhaps we can infer natural time bins by default later in the pursuit of making dataprep "smart", if we think this is important.
I agree with you on the tick formatting.

**Comment by jinglinpeng** [comment]
> @jinglinpeng Above I'm talking about the bin endpoints, not ticks. To give an example, suppose we have a dataset with a time column with values from November 4, 2019 to April 11, 2020. If we handle this as a numeric column and build a histogram, we would have bins like [Nov 4,Nov 29), [Nov 29, Dec, 22),.... In my opinion, it would be good for us to support the bins November, December, ..., April, ie using natural time intervals. My idea was to define the bin endpoints the same way as for a numeric column by default, and to give the user a parameter to specify the bins, eg "year", "month", "day". But perhaps we can infer natural time bins by default later in the pursuit of making dataprep "smart", if we think this is important.
> I agree with you on the tick formatting.

Ic, now I understand. Agree with you on the natural time interval .

**Comment by brandonlockhart** [comment]
For Jinglin's initial point 2., if we handle time series columns like numeric columns, we would get bins like this:

![Screen Shot 2020-04-12 at 6 18 01 PM](https://user-images.githubusercontent.com/25874021/79084750-47fa5100-7cea-11ea-80f8-563de072a498.png)

Personally, I don't like these bins, so I think we should consider only using natural time intervals. I propose by default we group the time series values by either year, quarter, month, week, etc, such that the number of groups is as close to the `bins` parameter value (default 10) as possible. We can give the user a parameter to specify the grouping time unit.
Tableau only supports natural time intervals when binning a time series column, and they default to grouping by 'year'. 

![Screen Shot 2020-04-12 at 6 20 08 PM](https://user-images.githubusercontent.com/25874021/79084758-53e61300-7cea-11ea-9345-275636107680.png)

I also think we should plot a line chart.
@jinglinpeng @jnwang @dovahcrow  @Waterpine do you have any thoughts or comments about this?

**Comment by jnwang** [comment]
I agree with all your points. 

How will it affect plot(df, x, bins)? For example, suppose a user has ten years’ data but want to change from grouping by year to by month?

**Comment by brandonlockhart** [comment]
I was thinking of introducing another parameter like `timebin` where the user can then do plot(df, x, timebin="month") in your example.  The reason is if people want to do something like plot(df, bins=20, timebin="month"), we need two parameters. The obvious downside is the user needs to learn another parameter, so if you or anyone thinks we don't need to support the scenario in my previous sentence, then I think we can just use `bins`, ie plot(df, x, bins="month"). It's also possible in the future for us to have a plot for plot(df, x, y) with _x_ datetime and _y_ numerical where we need to specify the bins on both column.

**Comment by jinglinpeng** [comment]
> plot(df, bins=20, timebin="month")

I think it would be better to distinguish it from bins. Looks the timebin is the scale of the time rather than something similar to bins (here bins controls the number of the displayed bins, while the timebin controls the valid startpoint/endpoint for time column). Maybe we need a better name such as timescale?  I think the number of parameters is not an issue, as many plotting tool has more parameters than us. We just need to make sure that the meaning of each parameter is clear to users.

**Comment by Waterpine** [comment]
I think introducing another parameter **timebin** may be better. Since parameter **bins** is numerical type. If we assign "month" to bins, users may feel confused.

**Comment by brandonlockhart** [comment]
For plot(df, x=time, y=numerical) I added a chart consisting of box plots by time intervals: 
![Screen Shot 2020-04-18 at 4 08 59 PM](https://user-images.githubusercontent.com/25874021/79673479-fa209580-818e-11ea-8f1c-b9940564037d.png)
For plot(df, x=time, y=categorical), we currently have the multiline chart of frequencies of the categorical values over time 
![Screen Shot 2020-04-18 at 4 22 18 PM](https://user-images.githubusercontent.com/25874021/79673706-f55ce100-8190-11ea-8d1b-6e19644d0ea0.png)
I'm thinking of adding a stacked bar chart like this 
![Screen Shot 2020-04-18 at 4 28 20 PM](https://user-images.githubusercontent.com/25874021/79673792-b1b6a700-8191-11ea-95bc-fd87b9c43350.png)
I think it could be easier to compare categories with respect to the whole in a stacked bar chart compared to the line chart. 
@jinglinpeng @jnwang @Waterpine please let me know any opinions and if there are any other time series plots we should support at this time.

**Comment by Waterpine** [comment]
I agree that we could add a stacked bar chart. It is really beautiful. Moreover, it could give us some interesting insights.

**Comment by dovahcrow** [comment]
It seems like at the high level, the problem we are facing is "attaching transformations to columns", e.g. for weekly `timebin` on daily dataframe, the input is 

    |     x      | y  |
    -------------------
    | 2020-01-01 | 10 |
    | 2020-01-02 | 10 |
    | 2020-01-03 | 10 |
    | 2020-01-04 | 10 |
    | 2020-01-05 | 10 |
    | 2020-01-06 | 10 |

And we first do a transformation that yields

    |     x      | y  |
    -------------------
    | 2020-01-01 | 40 |
    | 2020-01-05 | 20 |

And then directly plot it out.

Moreover, the transformation can be applied to both x and y thus adding parameters to the function makes everything clumsy.

I would suggest making these column transformations as a column name modifier.
`plot(df, x="x_name", y="y_name")`: We decide the best transformations applied to these two columns.
`plot(df, x=Column("x_name", bin="1w"), y="y_name")`: User can override transformations
`plot(df, x="x_name", y=Column("y_name", agg="sum"))`: Another example for showing group by x summing on y.
`plot(df, x="Bin(x_name, '1w')", y="Sum(y_name)")`: Syntax sugar for the above example.
