### ISSUE TITLE
The num_bins calculation is not correct for plot_missing when data size is small

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#137]
**Describe the bug**
I guess the computation of bin size is doing wrong on an edge case causing it becomes zero and throws out zero division exception.

**To Reproduce**

```python
df = pd.DataFrame(data=[[1,2,3]])
plot_missing(df)
```

**Expected behavior**
No exception is thrown out.

**Screenshots**
![image](https://user-images.githubusercontent.com/998606/79951194-1b9ead00-842d-11ea-810e-f939f6efcd07.png)

**Desktop (please complete the following information):**
 - OS: LInux
 - Browser: Chrome
 - Platform: VSCode
 - Platform Version: 1.44.1
 - Python Version: 3.7.5
 - Dataprep Version: 0.2.4

**Comment by Waterpine** [comment]
@jinglinpeng I have fixed this bug. Could you check it when you are free? Thanks!
<img width="1125" alt="屏幕快照 2020-12-09 上午11 28 25" src="https://user-images.githubusercontent.com/29000790/101570601-c17d4700-3a11-11eb-9f7c-7314243593f9.png">
