### ISSUE TITLE
Blog post for a comprehensive introduction to dataprep

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#142]
It would be better to have a blog post that introduces the dataprep, for people to understand what we are doing.

Some points from me:

* A video at the beginning for those don't like texts.
* What is this library and how it will be better than existing solutions. 
   * The effort on the code using `pandas + matplotlib` vs `dataprep.eda`.
   * The effort on the code using `requests` vs `dataprep.data_connector`.
   * The time spent, `pandas-profiling` vs `dataprep.eda`, and why.
* How to contribute/contact at the end of the blog

Any more ideas? @jnwang @jinglinpeng @peiwangdb @brandonlockhart

**Comment by jnwang** [comment]
I discussed it with Brandon last week. @brandonlockhart can you share with everyone your draft in the team channel on Discord?

**Comment by dovahcrow** [comment]
Closed: https://towardsdatascience.com/exploratory-data-analysis-dataprep-eda-vs-pandas-profiling-7137683fe47f
