### ISSUE TITLE
plot(df, x, y): keep the categorical order consistent in the output

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#148]
**Is your feature request related to a problem? Please describe.**
Currently the categorical order of the output of `plot(df, x = cat, y=cat)` is not consistent. For the nested_bat_chart, it sorts category by its frequency. See the fig. below:
<img width="957" alt="Screen Shot 2020-04-30 at 3 46 58 PM" src="https://user-images.githubusercontent.com/18078770/80766424-43130b00-8afa-11ea-8c67-3d6a2f6dfc65.png">

Usually I would like to compare the bar charts when calling `plot(df, x, y)`. Hence it would be more convenient to make the category order of the bar charts consistent. 

Besides, the order in the stacked_bar_chart and heat map is also not consistent. See the fig. below:
<img width="1078" alt="Screen Shot 2020-04-30 at 3 54 20 PM" src="https://user-images.githubusercontent.com/18078770/80766721-efed8800-8afa-11ea-8bae-ce45e2892985.png">
<img width="1024" alt="Screen Shot 2020-04-30 at 3 54 28 PM" src="https://user-images.githubusercontent.com/18078770/80766727-f2e87880-8afa-11ea-9664-bccdbc453e6d.png">

**Describe the solution you'd like**
Could we make all the output fig. (the bar charts in nest_bar_charts, the stacked_bar_chart and the heat map) using the same categorical order? For example, using the alphabetical order.

**Comment by dovahcrow** [comment]
Maybe it would be better to sort the bars first before breaking them down by `y`.
