### ISSUE TITLE
plot(df, x) error

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#150]
**Describe the bug**
The bug happened when running plot(df, x). It may be related to datatype. 

**Screenshots**
The dataset can be downloaded from [this link](https://www.dropbox.com/s/mv1waxnimiqxw35/flight_small.csv).

<img width="683" alt="Screen Shot 2020-05-08 at 8 41 30 PM" src="https://user-images.githubusercontent.com/1028970/81463186-58c4a800-916c-11ea-9dc0-d314da2c9665.png">

**Comment by dovahcrow** [comment]
I think this error is due to all the years are having the same value and `plot` is treating this column as numbers. There should be some way to stop calculating the KDE if all values are the same.

**Comment by jinglinpeng** [comment]
@jnwang @dovahcrow The error is raised by scipy when you compute the KDE with the same values. Maybe we detect this case first and directly show the hist. in the KDE plot tab?
