### ISSUE TITLE
plot(df, time, num, cat): using top k based on frequency could be misleading

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#151]
**Is your feature request related to a problem? Please describe.**

Since we show the groups with the highest frequency, the user could infer that the largest increase in Europe is due to the increase in the UK:

![Screen Shot 2020-05-09 at 9 15 06 AM](https://user-images.githubusercontent.com/25874021/81479004-a3c6d580-91d5-11ea-8871-8a000f3bd612.png)

Yet displaying all countries shows this is not the case

![Screen Shot 2020-05-09 at 9 17 29 AM](https://user-images.githubusercontent.com/25874021/81479095-25b6fe80-91d6-11ea-9028-febd4c0c772c.png)

**Describe the solution you'd like**
I wonder if top k should be computed with respect to the `agg` parameter. So in the above scenario, we would show the k countries with the largest sum of confirmed cases. We would need to make this clear in the how-to-guide for this plot.
Else, I think we would need a good rationale for using top k based on frequency in this context, perhaps across-plot consistency.

**Comment by dovahcrow** [comment]
How's the current top k calculated for a time series?

**Comment by brandonlockhart** [comment]
@dovahcrow we compute the frequency of each categorical value and select the k values with the highest frequency, ties are broken alphabetically.

**Comment by dovahcrow** [comment]
@brandonlockhart for time series, does that mean all the frequencies across different times are accumulated as one number for ordering?

**Comment by brandonlockhart** [comment]
@dovahcrow yes

**Comment by dovahcrow** [comment]
@brandonlockhart in the second plot, the curve of Montenegro is strictly higher than the England, which means the accumulative number should also be larger than the England so that Montenegro should be displayed in the first plot but actually not. Is it a bug?

**Comment by brandonlockhart** [comment]
@dovahcrow I'm not sure I understand what you're asking. It doesn't matter if a curve is strictly higher than another. The UK has more records in the dataset, therefore it is shown. Please let me know if I didn't answer your question.
