### ISSUE TITLE
plot(df, x) descriptive statistics

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#157]
**Task:** add the column statistics from pandas-profiling to `plot(df, x)`.

My proposal is to add another [tab](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#tabs) with the statistics like we have a tab for each visualization. Or is it important to see the statistics beside a visualization?
I think if we add a tab it could be created with Bokeh [Div](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#div), (or [Paragraph](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#paragraph) or [PreText](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#pretext)) which allows formatted text ([example](https://github.com/bokeh/bokeh/tree/master/examples/app/stocks)), but there are perhaps other possibilities.

Do we also want to add full dataset statistics like pandas-profiling? Perhaps we could add these at the top of the `plot(df)` output.

I think it's important to consider the time required to compute the statistics. We can consider `dask.compute(statistics)`, but should verify this is the most efficient approach. It would be ideal to perform minimal passes over the dataset in order to compute all the statistics.

**Comment by jinglinpeng** [comment]
Good job! I don't know whether it is necessary to show the full table stat., as user can call df.describe(), but we may display other information.  We could start with plot(df, x) by adding a tab. Later we could see whether it can be embedded with the plot (I feel that show stat. with the visualization together would be ideal).

The [example](https://github.com/bokeh/bokeh/tree/master/examples/app/stocks) looks good. I'm also seeing that there is a DataTable in Bokeh (https://stackoverflow.com/questions/37470415/display-a-pandas-data-frame-with-bokeh), does it worth to try?

**Comment by jnwang** [comment]
If the goal of plot(df) is to get an overview of the dataset, then it might be better to show full data stats to meet the user's expectations. Compared to df.describe(), we can do it faster and visualize better.

**Comment by brandonlockhart** [comment]
For plot(df, [numerical_column, datetime_column]), the plot does not grow wider, so it might be an efficient use of space, and more convenient for the user, to put the stats beside the visualization. But I think this will be effectively placing one panel beside another (the stats panel beside the visualizations panel), rather than having to toggle between tabs, so the output should be appropriate in both situations (ie, an easy change to switch from another hidden tab to beside the visualization).

For plot(df, categorical_column), the plot gets wider when ngroups is specified to be large. But I think it would also be okay to put the stats beside the visualization because if the user sets ngroups to be large, I think they would be focused on the visualization, and so they won't be frustrated scrolling to see the stats.

**Comment by jnwang** [comment]
I would recommend putting it in a new tag since we are adding auto-insights and how to guide later, which may require the side space.

**Comment by jinglinpeng** [comment]
> I would recommend putting it in a new tag since we are adding auto-insights and how to guide later, which may require the side space.

@jnwang  the how to guide and the auto-insight would both beside the visualization?

**Comment by jnwang** [comment]
They should be in the same tag as the visualization. They could be put on the side, bottom, or top.

**Comment by jinglinpeng** [comment]
> They should be in the same tag as the visualization. They could be put on the side, bottom, or top.

Got it. Just want to add anther solution to save the space: make the stat., the guide, and the auto-insight foldable, like the 'toggle details' in [pandas-profiling](https://pandas-profiling.github.io/pandas-profiling/examples/master/census/census_report.html) . Which one do you prefer? @jnwang  I.e., put the stat. the same tag as the visualization but fold it by default, or put it in a new tag?

**Comment by jnwang** [comment]
The reason that I want them to put in the same tag is that the user wants to see the insights (or how to guide) with the visualization at the same time. If a design can meet this requirement, it will be a good design, but it's unclear to me which design is the best.

**Comment by brandonlockhart** [comment]
This is a rough mockup idea. We could have the visualizations on the left and stats/insights/guide on the right.
![Screen Shot 2020-05-15 at 3 53 00 PM](https://user-images.githubusercontent.com/25874021/82102412-55797100-96c4-11ea-8d2a-fe7249f732b4.png)

**Comment by jnwang** [comment]
Great! Will stats be the same for line and hist? If so, it might be better to put it on the left-hand side, i.e., stats, line, hist? We can also have auto-insights for stats, like the percentage of missing values is so high.

**Comment by dovahcrow** [comment]
I'm thinking of something very similar to Brandon's design. The difference is that I think the how_to_guide can be a small circled "i"  button on the upper right corner of the plot, and shows the tooltip and the mouse is hovered upon. The reason is that the how-to-guide stuff usually won't be used very often and does not worth a whole tab to confuse the user.

**Comment by brandonlockhart** [comment]
@jnwang we're planning on showing the column's stats in a tab, so the stats will not change for different visualizations.
Sorry I should have given an example with our plots, the line and hist above was just example plots. @jnwang is this what you mean by putting the stats on the left-hand side?

![Screen Shot 2020-05-15 at 4 12 35 PM](https://user-images.githubusercontent.com/25874021/82103269-36301300-96c7-11ea-87cf-85193136fab2.png)

For auto-insights, I agree that many insights will be stats. This means that we could perhaps highlight the insightful stats in the stats tab, or show the auto-insights tab by default if there are interesting insights (rather than the stats tab by default). But if this side-by-side structure is sufficient, then the previous sentence is just formatting.
@dovahcrow I like your proposal, and I think we could add a circled "i" to each vis and put the how-to-guide in the hover tool of that circle. The only thing I'm thinking is if the user will want to look at the user guide when they type the function call (say for configuring parameters). And I also think once the user looks at the how-to-guide tab once, they will know what it is, and it will not confuse them in the future. Perhaps we should first decide the content of the how-to-guide, and then we can see what design is best (tab or circled "i").

**Comment by jnwang** [comment]
Sorry for the misleading msg. What I meant is to put stats together with histogram, KED plot, QQ normal plot, and box plot since each of them is one different way to understand the whole column. For each of them, we should have auto-insights. That is, the user can check what are the insights for stats, histogram, KDE plot, QQ normal plot, box plot, respectively. 

For the _how to guide_ feature, it could be similar to _verbose_ in python. By default, it is disabled. When the user wants to see it, she can pass it as an argument. 

Just my two cents.

**Comment by brandonlockhart** [comment]
@jnwang thanks for the clarification. It sounds like your proposing something like this
![Screen Shot 2020-05-15 at 4 59 03 PM](https://user-images.githubusercontent.com/25874021/82105013-020c2080-96ce-11ea-86b2-11e090a40e2c.png)
I like this design and that each tab is a different way to understand the column. I just wonder if the stats beside a visualization will help put the numbers into perspective or to understand them. Like if the variance is surprisingly large it could be the result of outliers; although it's easy to toggle between tabs to resolve this. I'm happy with this format though, we can start with this.
I like the verbose idea too.

**Comment by jnwang** [comment]
@brandonlockhart I see your point. Let's go with one design first and then make the final decision later.

**Comment by eutialia** [comment]
I have added some statistics to stats tab based on pandas-profiling's design.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/12697964/82399496-1cb20280-9a0a-11ea-8da4-8491e915fb64.png">

But there are some questions:

1. What else information do we need to show on this tab?
2. Do we need to trim down the decimal places to make the tab look better(which I already did)?

**Comment by jnwang** [comment]
May I suggest putting stats as the first tag?

For 1, it’s good enough for now.
For 2, yes. Please also test whether there is any formatting issue for very large values (eg 10000000) or very small values (0.0000001)?

**Comment by brandonlockhart** [comment]
Great job! To answer your questions, in my opinion
1. This is enough information
2. Yes, I propose the following rules for a number x:
a. if |x| ≥ 1,000,000 or |x|< 0.001, use scientific notation with at most 5 significant digits
b. else if |x| ≥ 1, round to at most 4 decimal places
c. else 0.001 ≤ |x| < 1, use at most 4 significant digits

My other thoughts are
1. If possible, format the statistic name and statistics in separate aligned columns like pandas-profiling does. I think it could be easier to read. We can widen the plot if necessary, and I would also like the horizontal lines separating the statistics if possible.
2. Highlight the insights red like pandas-profiling (eg missing values >0, zeros >> 0, large number of distinct values)

**Comment by eutialia** [comment]
I tried to use table to render stats tab, and because of the default behavior of Jupyter notebook the table element is rendered differently than plain text. However, text alignment is easier when using table.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/12697964/82526156-227e1580-9ae8-11ea-9a0a-7ca291dc4b42.png">
Also if we want to use table we need more space for every tab.

The question is, do we switch to table layout or we keep using plain text.

**Comment by brandonlockhart** [comment]
I prefer the table layout

**Comment by jinglinpeng** [comment]
Also prefer the table layout, which looks more clean.

**Comment by eutialia** [comment]
I have tweaked the layout of the table so it looks more compact and still informative. Also different notebook interface may have different styling behavior:
_Default browser:_
<img width="479" alt="image" src="https://user-images.githubusercontent.com/12697964/82605220-6fa2cb80-9b6a-11ea-8753-1e8b43dd1249.png">
_vscode_:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/12697964/82605228-73cee900-9b6a-11ea-9aa2-d8dfeb0f3e14.png">

What do you guys think?

**Comment by jnwang** [comment]
Looks very good. 

Two minor comments: 

1. Please add a space between a word and (. For example, Unique(%) --> Unique (%). 
2. Move **Quantile Statistics** and **Descriptive Statistics** down a little bit so that they are more close to the corresponding stats.

**Comment by brandonlockhart** [comment]
I think it looks good
