### ISSUE TITLE
eda.plot: support text analysis

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#159]
The issue is related to the task of supporting text analysis. The initial idea is that:

1. Have a type system, and support a type named 'text'.

2. plot(df): for text column, we show the word cloud.

3. plot(df, x): for text column, we show some information related to the text, such as the length distribution, the most common words and the statistics of Lowercase/Uppercase Letter.

For now, I think we should start from the type system, which is needed for multiple tasks. Please let me know how you think about the overall design. If we both agree, I will make another issue about the type system. @jnwang @dovahcrow @brandonlockhart @Waterpine @dylanzxc .

**Comment by jnwang** [comment]
It looks good to me. A minor comment: should we call it string or text? Personally, I prefer string.

**Comment by jinglinpeng** [comment]
> It looks good to me. A minor comment: should we call it string or text? Personally, I prefer string.

As we need to distinguish text from categorical, the string may be a little confusing? (categorical column could also be string column)

**Comment by jnwang** [comment]
This is a good point. Now I agree that text sounds better.

**Comment by dylanzxc** [comment]
According to today's discussion:

Option 2: Generate word cloud using the existing licensed library, and add visualization or descriptive statistics as new tabs in plot(df.x).

What are the necessary visualizations do you think we need to include, besides frequency bar chart?

**Comment by jinglinpeng** [comment]
> According to today's discussion:
> 
> Option 2: Generate word cloud using the existing licensed library, and add visualization or descriptive statistics as new tabs in plot(df.x).
> 
> What are the necessary visualizations do you think we need to include, besides frequency bar chart?

I think word-cloud, bar chart, the length distribution, and other information in pandas-profiling. Let us first get word-cloud, bar chart and length distribution done.

**Comment by dylanzxc** [comment]
After the discussion with Jinglin, We think, for now, besides the existing stats, bar chart, piechart tabs for categorical data analysis, we should include word cloud, words frequency bar chart(corresponding to the word cloud), length distribution, scripts(show the most occurring scripts) and add text stats to the current stats tab. @jnwang @dovahcrow @jinglinpeng @brandonlockhart @Waterpine 

Stats tab include for sections:
![image](https://user-images.githubusercontent.com/56427336/84199868-b7768d80-aa5a-11ea-8fcf-e4e291e0d6b7.png)
Word Cloud:
![image](https://user-images.githubusercontent.com/56427336/84199937-cf4e1180-aa5a-11ea-93db-06f10a309deb.png)
Word Frequency Bar chart:
![image](https://user-images.githubusercontent.com/56427336/84199991-decd5a80-aa5a-11ea-9a45-92bb902d78d2.png)
Length:
![image](https://user-images.githubusercontent.com/56427336/84200458-b4c86800-aa5b-11ea-9634-33e9bfde2721.png)
Scripts:
![image](https://user-images.githubusercontent.com/56427336/84200492-c3af1a80-aa5b-11ea-959d-dca685a86ebe.png)

**Comment by jnwang** [comment]
Looks cool!

My only comment is on quantile stat. How are you going to compute it for non-numerical attribute?

**Comment by dylanzxc** [comment]
My plan was treating each element as one percentile. But this yields a potential problem that one element could be a long paragraph which is hard to show in stats. Do you have any suggestions for this? 

We want to show three-level stats information: sentence level(Length), word level, letter level(Letter). Do you think quantile stats belong to word level or sentence level? @jnwang

**Comment by jnwang** [comment]
"Quantile stat" means word frequency? Then, maybe we should rename it as Word Frequency.
