### ISSUE TITLE
eda.basic: plot(df) statistics

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#166]
_This feature is from the post by @jnwang in https://github.com/sfu-db/dataprep/issues/157#issuecomment-629354764_

I propose to start with the Overview section from pandas-profiling, and output this information at the top of `plot(df)`. The Reproduction section to me seems more useful in a report, so I don't think we need to include it. We can include some auto-insights in this section (like Warnings in pandas-profiling), but I think that is a separate issue.
I propose a simple layout:

![Screen Shot 2020-05-24 at 10 26 58 PM](https://user-images.githubusercontent.com/25874021/82781100-cbd94a00-9e0d-11ea-9d00-52f160472354.png)

If we want to plan where to put insights, I think we can have tabs like this:

![Screen Shot 2020-05-24 at 10 34 34 PM](https://user-images.githubusercontent.com/25874021/82781518-d5af7d00-9e0e-11ea-94e9-a1e206880ac6.png)

Let me know if you have any comments @jnwang @jinglinpeng @dovahcrow @Waterpine @eutialia

**Comment by jnwang** [comment]
Very well design. Looks good to me.

**Comment by jinglinpeng** [comment]
Nice. Looks good to me.

**Comment by dovahcrow** [comment]
If the insights are related to the plots, should it be put with the plots? Otherwise users need to switch tabs back and forth to read the insights with the plots.

**Comment by brandonlockhart** [comment]
Good point @dovahcrow, I agree that insights should go with their corresponding plots. I was thinking it might be useful to state insights in a tab so the user can get a quick summary of the insights, or if their dataset has many columns then this could highlight some important columns. Also, I was thinking it might be informative to give some [insights](https://www.microsoft.com/en-us/research/uploads/prod/2016/12/Insight-Types-Specification.pdf) like trend or clustering that don't necessarily have a corresponding plot in `plot(df)`. 

@dovahcrow maybe, for now, we can use the first layout (first image above). It will be easy to transfer the overview stats into a tab if we want to show insights like this in the future.

**Comment by eutialia** [comment]
The result on a real dataset looks like this:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/12697964/82950216-c6891600-9f59-11ea-8fba-96579f61901b.png">
<hr>
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/12697964/82950244-d0127e00-9f59-11ea-8734-6e24a699716a.png">

Any suggestions?

**Comment by brandonlockhart** [comment]
It looks good to me

**Comment by jnwang** [comment]
Is it easy to allow the user to fold and unfold the two tables for Data Statistics and Variable Type?

**Comment by brandonlockhart** [comment]
@jnwang we could try something like this

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/25874021/83050494-81b8ba00-a001-11ea-9c10-209c5021cd14.gif)

**Comment by jnwang** [comment]
I like it! Thanks for addressing my comment!
