### ISSUE TITLE
print(dataprep.__version__) bug

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#176]
**Describe the bug**
My dataprep version is 0.2.6. But when running `dataprep.__version__`, it shows 0.2.8. 

**To Reproduce**

```python
import dataprep
print(dataprep.__version__)
```

**Screenshots**
<img width="235" alt="Screen Shot 2020-06-02 at 11 06 56 PM" src="https://user-images.githubusercontent.com/1028970/83601752-0a65b780-a526-11ea-9841-674d1ad8f463.png">

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome
 - Jupyter Notebook 7.8.0
 - Python Version 3.8.4
 - Dataprep Version 0.2.6

Credit: @lydiazheng

**Comment by dovahcrow** [comment]
This is fixed in develop branch. Do you think we should make a new release?

**Comment by jnwang** [comment]
Thanks for your quick response. We can get it fixed in the next release.
