### ISSUE TITLE
Graph shrink problem with plot(df,x) for categorical data in certain web browsers. 

### ISSUE THREAD

**Issue by dylanzxc** [sfu-db/dataprep#179]
When plot(df, x) where x is a categorical column, all the charts are shrunk in Google chrome, Microsoft Edge. 

Brandon suspected that the legend of the pie chart makes the pie plot small, and for some reason, Bokeh needs to make the same width for the plots in all tabs. 

However, this shrink problem doesn't happen for Linghao with Mac Safari.

![image](https://user-images.githubusercontent.com/56427336/84232989-48268b00-aaa6-11ea-8af5-8c24818d72d1.png)
![image](https://user-images.githubusercontent.com/56427336/84232995-4d83d580-aaa6-11ea-891e-278c15903408.png)

**Comment by dovahcrow** [comment]
@dylanzxc Can you link the issue you reported in bokeh repo to here?

**Comment by dylanzxc** [comment]
https://github.com/bokeh/bokeh/issues/10184

**Comment by dylanzxc** [comment]
After the discussion with bokeh team. We have two options to solve this problem. One is using bokeh.layouts.row() to keep each plot independent.
![image](https://user-images.githubusercontent.com/56427336/84842254-7dc4fa00-aff9-11ea-8b19-34bb4acdd01c.png)
![image](https://user-images.githubusercontent.com/56427336/84842264-86b5cb80-aff9-11ea-9946-1676a19ab4d8.png)
Another way is we can limit the length of each label in the legend just like what we did to the histogram and bar_chart.
![image](https://user-images.githubusercontent.com/56427336/84842352-b95fc400-aff9-11ea-8cc1-7b94f34f6641.png)
![image](https://user-images.githubusercontent.com/56427336/84842362-c1b7ff00-aff9-11ea-96e9-a59590337c57.png)
How do you think? @dovahcrow @jinglinpeng @brandonlockhart

**Comment by brandonlockhart** [comment]
I think we should limit the length of each label and use row() as well
