### ISSUE TITLE
eda.plot_missing: Automatically marking missing values

### ISSUE THREAD

**Issue by Waterpine** [sfu-db/dataprep#180]
**Task**: Automatically marking missing values(one of the tasks of #168)

We need to define a list of values and assume that they are missing values by default rather than using df.notnull(). The list could contain but not only contain null, Nan, None. For example, if it is an empty string, it should be treated as a missing value.

Time: 2020.6.15 - 2020.6.21

@Sanjana12111994

**Comment by jinglinpeng** [comment]
@jnwang @Waterpine @dovahcrow  I think we may need some ideas of how this functionality is different from the `na_values` parameter in [`pd.read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)?

**Comment by jnwang** [comment]
Good point! I did not know the existence of the `na_values` parameter. I think what we need is to add `na_values` to plot_missing. It's good that pandas has already given a good list of default null values: 

<img width="649" alt="Screen Shot 2020-06-12 at 1 08 11 PM" src="https://user-images.githubusercontent.com/1028970/84542223-d91b8300-acad-11ea-97b2-0d8d30db2a86.png">

**Comment by dovahcrow** [comment]
Yea I think the null list from pandas is comprehensive enough for now. 

On the implementation side, I think we can store the info in the dtypes and do the `drop null` lazily on-site by only computing the null index for computation required columns.

**Comment by jinglinpeng** [comment]
@jnwang @dovahcrow Do we plan to add other null strings in the future? If not, looks we do not need to implement our own marking of missing values, as typically the missing value has been marked in the dataframe.

**Comment by jnwang** [comment]
Is it still true if the dataframe is **not** created through pd.read_csv? If not, we need to have our own implementation. 

`as typically the missing value has been marked in the dataframe.`

**Comment by jinglinpeng** [comment]
> Is it still true if the dataframe is **not** created through pd.read_csv? If not, we need to have our own implementation.
> 
> `as typically the missing value has been marked in the dataframe.`
Ic. Now I agree. There are multiple ways to create a dataframe, such as from sql, from json.
