### ISSUE TITLE
Data Connector Promotional Video

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#189]

**Comment by pallavibharadwaj** [comment]
To be uploaded - [Data Connector Promo Video](https://drive.google.com/file/d/10a6lFrqnKo1NWp1pUjnUqo8FXqG0EPWa/view?usp=sharing)

**Comment by dovahcrow** [comment]
Uploaded! https://www.youtube.com/watch?v=EaKeN7TgC7g
