### ISSUE TITLE
Make Data Connector use async/await

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#192]
**Is your feature request related to a problem? Please describe.**
Currently, Data Connector uses synchronized requests to fetch the data. In order to make the request parallel, it would be easier to first convert the synchronized fetch into asynchronized one.

**Describe the solution you'd like**
Instead of using requests in Data Connector, use another async request library.
However, the query method should be still synchronized, which means it should call the eventloop at the end of the function.

**Comment by kla55** [comment]
Hello

**Comment by dovahcrow** [comment]
I just realized this one needs some more works to be compatible with Jupiter. @kla55 I'll modified something on this PR.

**Comment by dovahcrow** [comment]
This feature will allow a user to issue concurrent requests to fetch the data. 

In Jupyter, he can do
```python
df = await dc.query("businesses", term="ramen", location="vancouver")
```
to get the data concurrently (note the `await`, this is the API breaking change introduced in this PR).

He can also limit how "concurrent" he wants to have, e.g. 3 req/sec by
```python
df = await dc.query("businesses", term="ramen", location="vancouver", _concurrency=3)
```

The query function has different behavior in standalone python because you cannot directly run `await` in a standalone python.

In standalone python, a user do this (without `await`) to get a dataframe,
```python
df = dc.query("businesses", term="ramen", location="vancouver")
```

The user can always override the default behaviour by providing the `_async` parameter
```python
# _async = True returns an awaitable
df = await dc.query("businesses", term="ramen", location="Vancouver", _async=True) 
```
```python
# _async = False directly returns a dataframe.
df = dc.query("businesses", term="ramen", location="Vancouver", _async=False)
```

**Comment by jnwang** [comment]
I have a couple of questions.

1. I am a bit confused about the behavior of `_concurrency`.

For example, what will happen after running the following code? Does it mean that for all future requests called via this `dc` object,  _concurrency is always 3? In this case, does it make more sense to do dc.set_concurrency(3) rather than put it as an argument for dc.query()?

```python
 `df = await dc.query("businesses", term="ramen", location="vancouver", _concurrency=3)
```

2. This sounds a bit strange to me. How can a user issue multiple keywords in parallel in standalone python (e.g., pycharm)?

> The query function has different behavior in standalone python because you cannot directly run await in a standalone python.

3. Can you give me a concrete situation when a user wants to override the default behaviour by providing the _async parameter?

**Comment by dovahcrow** [comment]
1. good point. I think we can just do things like the auth parameter: each query function inherits the concurrency setting from the Connector object.

2. First, no matter it is standalone python or jupyter, when you try to issue multiple queries in parallel, you always do things like this:
```python
pending_result = asyncio.gather(
    dc.query("business", term="ramen", location="vancouver"), 
    dc.query("business", term="sushi", location="vancouver")
)
```

depending on the platform you are running the code, Jupyter:
```python
df1, df2 = await pending_result
```

standalone python:
```python
df1, df2 = asyncio.run(pending_result)
```

3. There's no point to override the `_async` on Jupyter, but on standalone python, a user may want to 1. write one line of code to get the data, thus `_async=False` (default behavior). 2. use Connector in a system and run multiple queries in parallel, thus `_async=True` (use the method in point 2).

The default behavior covers the most common use-cases in different platforms IMO.
