### ISSUE TITLE
Insights for plot(df) and plot(df,x). Stage 1

### ISSUE THREAD

**Issue by dylanzxc** [sfu-db/dataprep#203]
The new insight plan after Jun 6th meeting:

In plot(df) we will include distribution-related insights for each feature. All the insights will be displayed in one div. 

1. variable has a constant value
2. variable contains a lot of zeros
3. varaible has a high cardinality
4. variable contains a lot duplicates 
5. variable is highly skewed
6. variable's kurtosis level
7. variable contains infintie values
8. variable has a constant length 
9. variable is uniformaly distributed 
10. correlation between different variables' ditributions(KL Divergence)

**Comment by dylanzxc** [comment]
Hi teams,

I have made another design for the insights in plot(df). But a delay problem occurred with button-click in the new design. The potential cause could be the complex layout settings in our code `column(button, stats, gird(for fig in figs: column(row(title, button), insight, fig))`. I have sent a message to Bokeh to see if they can find the root cause. Otherwise, another attempt we can do is no longer using grid() in plot(df) and recompose all the plots with row and column only. 

But before solving the delay problem, I'd like to know how do you think about the current design? The color, fontsize, fonttype of button and titles are changeable. 
![example5](https://user-images.githubusercontent.com/56427336/85813646-9da29f00-b718-11ea-8a2f-b42bd4d64789.gif)

@jnwang @jinglinpeng  @dovahcrow  @brandonlockhart  @eutialia

**Comment by jnwang** [comment]
Good job. A couple of comments:

- The green button looks big to me. Replace it with a small [icon](https://www.google.com/search?q=icon+insight&sxsrf=ALeKk03bESnF8tiYJcFPY-idNCNVCGCwZQ:1593147418643&source=lnms&tbm=isch&sa=X&ved=2ahUKEwif39nP2J7qAhXIsZ4KHdNNAAoQ_AUoAXoECA0QAw&biw=1304&bih=683) ? 

- Do not show the icon when there is no insight

- When the user moves the mouse over the icon, show the insights in a transparent pop-up window like tooltip. 

- I don't know whether it's easy to put the number of insights into the icon. If not, we can remove the number and show the icon only.

**Comment by jnwang** [comment]
To make my point, the design is something similar to the following screenshot but with an insight icon.

https://altair-viz.github.io/gallery/bar_chart_with_highlighted_bar.html

<img width="742" alt="Screen Shot 2020-06-26 at 11 46 54 AM" src="https://user-images.githubusercontent.com/1028970/85890748-d6875600-b7a2-11ea-90fd-d367dd9e8731.png">

**Comment by dylanzxc** [comment]
Yeah, I understand your ideas, Professor. 

The following three are easy to achieve.
> * The green button looks big to me. Replace it with a small [icon](https://www.google.com/search?q=icon+insight&sxsrf=ALeKk03bESnF8tiYJcFPY-idNCNVCGCwZQ:1593147418643&source=lnms&tbm=isch&sa=X&ved=2ahUKEwif39nP2J7qAhXIsZ4KHdNNAAoQ_AUoAXoECA0QAw&biw=1304&bih=683) ?
> * Do not show the icon when there is no insight
> * I don't know whether it's easy to put the number of insights into the icon. If not, we can remove the number and show the icon only.


However, the pop-up demand is not-straight forward to fulfill in bokeh. 
> * When the user moves the mouse over the icon, show the insights in a transparent pop-up window like tooltip.

I'm asking for help from the bokeh team. For now, the reply I got is, bokeh can generate a pop-up alert window like the following gif. But this is not the type of pop-up window we want. I'm still communicating with them. If they say this is not feasible with bokeh then we need to consider developing our own HTML tool to render the plot.
![example8](https://user-images.githubusercontent.com/56427336/85900098-10148d00-b7b4-11ea-8da6-71de1ab15c34.gif)
