### ISSUE TITLE
Data Connector: Generate configuration files from JSON:API response examples

### ISSUE THREAD

**Issue by juandavidospina** [sfu-db/dataprep#206]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For a particular API endpoint, generate a partial or full configuration file from a JSON:API response example. Depending on the example, attributes like the endpoint URL, request parameters, pagination information, and response object names may be obtained from a response example. 

E.g. For the Spotify API - Search endpoint, the following JSON:API response example is published on the Spotify API website (see: https://developer.spotify.com/documentation/web-api/reference/search/search/). This JSON:API response example could be used as input to obtain relevant attributes for generating a Data Connector for this endpoint:

```json
{

  "artists": {
    "href": "https://api.spotify.com/v1/search?query=tania+bowra&offset=0&limit=20&type=artist",
    "items": [ {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
      },
      "genres": [ ],
      "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
      "id": "08td7MxkoHQkXnWAYD8d6Q",
      "images": [ {
        "height": 640,
        "url": "https://i.scdn.co/image/f2798ddab0c7b76dc2d270b65c4f67ddef7f6718",
        "width": 640
      }, {
        "height": 300,
        "url": "https://i.scdn.co/image/b414091165ea0f4172089c2fc67bb35aa37cfc55",
        "width": 300
      }, {
        "height": 64,
        "url": "https://i.scdn.co/image/8522fc78be4bf4e83fea8e67bb742e7d3dfe21b4",
        "width": 64
      } ],
      "name": "Tania Bowra",
      "popularity": 0,
      "type": "artist",
      "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
    } ],
    "limit": 20,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 1
  }
}
```
**Describe alternatives you've considered**
Gather this information through web scrapping, however web scraping implementations can become obsolete when layout changes are made on source webpages.

**Additional context**
None.

**Comment by peiwangdb** [comment]
Thanks for the description @juandavidospina ! Above included is a json response returned by the API. In the best case, this part can be used to generate the response part in our config file. An alternative is to issue a few queries and convert returned json file to csv and then extract the schema. Note that there are also request and version parts in the config file (like https://github.com/sfu-db/DataConnectorConfigs/blob/master/dblp/publication.json). We can try to tackle them separately.

**Comment by dovahcrow** [comment]
Now that the generator is roughly implemented, I will close this issue and create a new epic for generator & UI implementation in this fall.
