### ISSUE TITLE
plot_missing(df) error: heatmap is empty when variable is singular

### ISSUE THREAD

**Issue by eutialia** [sfu-db/dataprep#216]
**Describe the bug**
Heatmap has no data to present when variable is singular.

**To Reproduce**

```python
from dataprep.eda import plot_missing
import pandas as pd
df = pd.read_stata('http://www.stata-press.com/data/r15/auto2.dta')
plot_missing(df)
```

**Expected behavior**
Maybe heatmap shouldn't be rendered in this situation?

**Screenshots**
<img width="514" alt="image" src="https://user-images.githubusercontent.com/12697964/86526579-ba428380-be4a-11ea-8287-4fd775f51194.png">

**Comment by jinglinpeng** [comment]
I think it would be better to keep all the plots even when it does not contain missing values. In the future, we can allow user set whether to show a plot or not, and by default we show all the plots. This output may be more expected and manageable.

**Comment by jnwang** [comment]
Can anyone take a look at how missingno handles this special case? It would be better to be consistent with an existing tool?

**Comment by dovahcrow** [comment]
@jnwang They show an empty heatmap.

**Comment by dovahcrow** [comment]
How about I make it empty like in #234?

**Comment by jnwang** [comment]
Looks good - please mention it in the document as well.
