### ISSUE TITLE
Plot function returns python html object and doesn't display anything

### ISSUE THREAD

**Issue by WestJackson** [sfu-db/dataprep#222]
**Describe the bug**
I am trying to follow the first example use of the plot function for a data frame. When I utilize Plot, I get returned the object "<IPython.core.display.HTML object> instead of being displayed the plot.

**To Reproduce**

```python
import os
import pandas as pd
import IPython
from dataprep.eda import plot

os.chdir('/Users/XX/XX/Predictive Modeling/') 
dataframe = pd.read_csv('lead_raw_data.csv', sep=',', header=0, na_values = [' ?'])
# print(dataframe) #properly prints my dataframe
plot(dataframe).show()
```

**Expected behavior**
I want this to show the normal plot display.
Instead I get returned a "<IPython.core.display.HTML object>"

**Desktop (please complete the following information):**
 - OS: MacBook Pro recent version
 - Browser chrome as primary for Pycharm
 - Platform Pycharm Professional
 - Platform Version 
 - Python Version 3.7.6
 - Dataprep Version recent

**Comment by jinglinpeng** [comment]
Thanks @WestJackson for the bug report. Looks there is no good solution to display html in consoles. Did you consider run code in Jupyter notebook? If this is not possible and you want to open the fig. in Browser, you could first save the fig. to html and then open the html from Pycharm.
