### ISSUE TITLE
Data_connector: Add support for fintech API

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/dataprep#224]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- [ ] Select 2 fintech APIs
- [ ] Implementation of the first config
- [ ] Implementation of the second config

**Describe alternatives you've considered**

**Additional context**

**Comment by dovahcrow** [comment]
Implemented [Finnhub](https://github.com/sfu-db/DataConnectorConfigs/tree/master/finnhub) (contains 10 endpoints).
