### ISSUE TITLE
plot(df, x) error when using connector

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#225]
**To Reproduce**

The following code raises an error:
`from dataprep.data_connector import Connector`
`from dataprep.eda import plot`
`dc = Connector("dblp")`
`df = dc.query("publication", q = "sigmod 2020", _count = 1000)`
`plot(df, "venue")`

**Screenshots**
<img width="1132" alt="Screen Shot 2020-07-03 at 8 19 05 AM" src="https://user-images.githubusercontent.com/18078770/86977863-67124e80-c132-11ea-9371-1f759295065f.png">

**Comment by jinglinpeng** [comment]
Please take a look at this issue. @dovahcrow @peiwangdb 
Looks `dc.query` now returns a coroutine object rather than df. Any idea of how this can be processed in eda?
![image](https://user-images.githubusercontent.com/18078770/92551438-d7148200-f212-11ea-9746-0662f0ab65b3.png)

**Comment by dovahcrow** [comment]
@jinglinpeng 
```python
from dataprep.connector import Connector
from dataprep.eda import plot
dc = Connector("dblp")
df = await dc.query("publication", q = "sigmod 2020", _count = 1000)
plot(df, "venue")
```
