### ISSUE TITLE
Design the solution for auto generating config files from examples (stage 1)

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#227]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like:**

We aim to design a functionality in Data Connector that will allow Dataprep's users to generate specific Data Connector configuration files suited to the particular API endpoint that they want to consume.

*Scenario 1:*

A configuration file could be created from one or more HTTP request examples. For this purpose, a _config generator_ object can be created taking as input one or more request examples. The `"request_examples"` parameter can be a string or a collection of strings, each one representing an HTTP request example, e.g. a `GET` request or a `POST` request. 
This method: (1) Obtains and parse relevant information from the request examples, (2) Performs one or more HTTP requests to the endpoints included request examples, (3) Receive and parse the JSON/XML response for the purpose of extracting the schema information and generating the configuration file.
_The result of executing `ConfigGenerator(request_examples)` is the generated runnable configuration file.
And please consider how and where to store the generated file carefully._

```python
cg = ConfigGenerator(request_examples)
```

_To demonstrate, please show examples of how to generate config file for DBLP and Open library API with this code and how to use the generated file and data_connector.query() to issue queries and get data.
It seems tokenparams APIs can also be supported by this interface, so please try the ones in https://github.com/sfu-db/dataprep/issues/209._

*Scenario 2:*

A configuration file can be generated from existing configuration files as well. The user can specify a folder containing one or more configuration files already created to retrieve data from one site (e.g. Twitter), or a specific configuration file:

```python
cg = ConfigGenerator("./myconfigfiles/twitter")
```

or

```python
cg = ConfigGenerator("./myconfigfiles/twitter/tweets.json")
```
Then, the user could output the configuration to a string or to a JSON file (configuration file), as follows:

```python
# Output to a string
json_string = cg.to_string()
```
or

```python
# Output to a JSON configuration file
cg.to_file("./myconfigfiles/myconfig.json")
```

*Scenario 3:*

For creating a configuration file with authentication properties, the user can proceed as follows:

```python
#Bearer token
dict_auth_params={"access_token":"<my_access_token>"}
cg = ConfigGenerator(request_examples, auth_type = "bearer", _auth_params = dict_auth_params)
```

```python
#API Key
dict_auth_params={"client_id":"<my_client_id>", "client_secret":"<my_client_secret>"}
cg = ConfigGenerator(request_examples, auth_type = "API_key", _auth_params=dict_auth_params)
```

```python
#OAuth 2.0 - Client Credentials Grant Type
dict_auth_params={"access_token":"<my_access_token>"}
cg = ConfigGenerator(request_examples, auth_type = "OAuth2_CC", _auth_params=dict_auth_params)
```
```python
#No Authentication
cg = ConfigGenerator(request_examples)
```

For creating a configuration file with pagination properties, the user can proceed as follows:

```python
#Limit (offset) pagination
# The following configuration will be assumed: 
```

```json
  "pagination":{
            "type":"limit",
            "anchor_key":"offset",
            "count_key":"limit",
            "max_count": "<defined by the user>"
        }
```

```python
dict_pag_params =  {"max_count": 50 }
cg = ConfigGenerator(request_examples, pag_type = "limit", _pag_params=dict_pag_params)

#Cursor (keyset) pagination
# The following configuration will be assumed: 
```
```json
 "pagination":{
            "type":"cursor",
            "count_key":"maxResults",
            "max_count": "<defined by the user>"
        }
```
```python
dict_pag_params =  {"max_count": 50 }
cg = ConfigGenerator(request_examples, pag_type = "cursor", _pag_params=dict_pag_params)


# Seek pagination
# The following configuration will be assumed: 
```
```json
 "pagination":{
            "type":"seek",
            "count_key":"maxResults",
            "max_count": "<defined by the user>",
            "after_id":  "<defined by the user>"
        }
```
```python
dict_pag_params =  {"max_count": 50, "after_id": 50 }
cg = ConfigGenerator(request_examples, pag_type = "seek", _pag_params=dict_pag_params)

#No pagination
cg = ConfigGenerator(request_examples)
```

**Comment by juandavidospina** [comment]
Is your feature request related to a problem? Please describe.
No.

Describe the solution you'd like:

We aim to design a functionality in Data Connector that will allow Dataprep's users to generate specific configuration files suited to the particular API endpoint that they want to consume.

A config generator can be created from one one more request examples. "request_examples" parameter can be a string or a collection of strings, each one representing an HTTP request example, e.g. a get request or a post request. 
This method obtains relevant information from the request examples and performs one or more HTTP request to the specified  endpoint. Each response received is parsed to extract the schema information and the information is stored in memory.

`cg = ConfigGenerator(request_examples)`

Configuration files can be generated from existing configuration files as well. The user can specify a folder containing configurations files belonging to one site (e.g. Twitter), or an specific configuration file:

`cg = ConfigGenerator("./myconfigfiles/twitter")`

or

`cg = ConfigGenerator("./myconfigfiles/twitter/tweets.json")`

Then, the user can output the configuration file to a string or to a JSON file, as follows:

`json_string = cg.to_string()`

or

`cg.to_file("./myconfigfiles/myconfig.json")`

For creating a configuration file with authentication properties, the user can proceed as follows:

`#Bearer token`
`dict_auth_params={"access_token":"my_access_token"}`
`cg = ConfigGenerator(request_examples, auth_type = "bearer", _auth_params=dict_auth_params)`

`#API Key`
`dict_auth_params={"client_id":"my_client_id", "client_secret":"my_client_secret"}`
`cg = ConfigGenerator(request_examples, auth_type = "API_key", _auth_params=dict_auth_params)`

`#OAuth 2.0 - Client Credentials Grant Type`
`dict_auth_params={"access_token":"my_access_token"}`
`cg = ConfigGenerator(request_examples, auth_type = "OAuth2_CC", _auth_params=dict_auth_params)`

`#No Authentication`
`cg = ConfigGenerator(request_examples)`

For creating a configuration file with pagination properties, the user can proceed as follows:

`#Limit (offset) pagination`
# The following configuration will be assumed: 
```
  "pagination":{
            "type":"limit",
            "anchor_key":"offset",
            "count_key":"limit",
            "max_count": <defined by the user>
        }
```
`dict_pag_params =  {"max_count": 50 }`
`cg = ConfigGenerator(request_examples, pag_type = "limit", _pag_params=dict_pag_params)`

`#Cursor (keyset) pagination`
# The following configuration will be assumed: 
```
 "pagination":{
            "type":"cursor",
            "count_key":"maxResults",
            "max_count": <defined by the user>
        }
```
`dict_pag_params =  {"max_count": 50 }`
`cg = ConfigGenerator(request_examples, pag_type = "cursor", _pag_params=dict_pag_params)`

`# Seek pagination`
# The following configuration will be assumed: 
```
 "pagination":{
            "type":"seek",
            "count_key":"maxResults",
            "max_count": <defined by the user>,
            "after_id":  <defined by the user>
        }
```
`dict_pag_params =  {"max_count": 50, "after_id": 50 }`
`cg = ConfigGenerator(request_examples, pag_type = "seek", _pag_params=dict_pag_params)`

`#No pagination`
`cg = ConfigGenerator(request_examples)`

**Comment by dovahcrow** [comment]
Cool! I think maybe it is better to not crowd the examples with the existing config file in the same parameter.
Instead, this might be better:
```
class ConfigGenerator:
    def __init__(self, config: Union[None, str, TextIO] = None) -> None: ...

    def add_example(self, example: str, _auth: Optional[Any] = None) -> None: ...

    def generate(self) -> str: ...

    def to_file(self, path: Path): ...
```

**Comment by peiwangdb** [comment]
@juandavidospina I refined the definition above for scenario 1. We can start making a prototype for this scenario.

**Comment by peiwangdb** [comment]
Shall we avoid the to_file method and set the target dir as a parameter for ConfigGenerator() by default?
@juandavidospina @dovahcrow

**Comment by dovahcrow** [comment]
The first parameter of `ConfigGenerator` can be both a URL or a file path which looks weird to me. I would prefer adding examples in a separate function.

**Comment by dovahcrow** [comment]
@peiwangdb 

> Shall we avoid the to_file method and set the target dir as a parameter for ConfigGenerator() by default?
> @juandavidospina @dovahcrow

This will make a GUI hard to build. if we keep the to_file, it can be directly mapped to a GUI button.

**Comment by dovahcrow** [comment]
For scenario 2 I think we can postpone it for later since it requires a little bit more design for the conflict resolving algorithm.

**Comment by dovahcrow** [comment]
Hi @juandavidospina, can you write down the final design here? Just code skeleton is enough. E.g.

**Comment by juandavidospina** [comment]
Next, you can find the final design for the stage 1:

```python

def create_config(example: str) -> 'ConfigGenerator':

class ConfigGenerator:
    def __init__(self) -> None: ...

    def create_configuration(self, request_example: str) -> 'ConfigGenerator': ...

    def _request_tokenizer(self, request_example: str) -> None: ...

    def _execute_request(self) -> None: ...

    def _create_config_file_representation(self) -> None: ...

    def save(self, filename: str) -> None:  ...

    def to_string(self) -> str: ...
```
