### ISSUE TITLE
'numpy.float32' object has no attribute 'is_integer'

### ISSUE THREAD

**Issue by twsl** [sfu-db/dataprep#231]
**Describe the bug**
I tried to load a dataset with explicit data types set to improve memory consumption. dataprep apparently expects a float, not the np.float32 data type and doesnt check either.

**To Reproduce**
```python
import numpy as np
import pandas as pd
from dataprep.eda import plot
df_acc = pd.read_csv('../data/acc.csv', 
                        sep = ',',
                        dtype={'x': np.float32, 'y': np.float32, 'z': np.float32})
plot(df_acc)
```

**Expected behavior**
Perform eda without issues.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Platform: Jupyter Notebook
 - Platform Version 6.0.3
 - Python Version: 3.6.10
 - Dataprep Version: 0.2.8

**Comment by jnwang** [comment]
Thanks @twsl for this big report. @jinglinpeng is looking into it. We will get it fixed as soon as possible.

**Comment by jinglinpeng** [comment]
Thanks @twsl for the bug report! This bug is fixed in [this PR](https://github.com/sfu-db/dataprep/pull/202 ) worked by @eutialia. It is now under review and will be released very soon!
