### ISSUE TITLE
Convert the documentation to jupyter notebook & update the output & apply bokeh theme

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#235]
Currently, these part of the documentations are written in rst and is not updated for our new features. It would be better to do an update and also migrate to ipynb for easy maintenance.

**Comment by jnwang** [comment]
I also agree that our current document style does not look very nice. Can we switch to something like https://docs.bokeh.org/en/latest/docs/user_guide/data.html#userguide-data ?

**Comment by dovahcrow** [comment]
They make their own theme for sphinx.

We have 2 options:

1. Find another theme that looks beautiful or just use the bokeh theme.
2. Spend some effort to make our own theme.



Regards,
Weiyuan Wu

---
Weiyuan Wu | PhD Student
a: SFU-DB | 8888 University Dr. | Burnaby, BC, CA
e: youngw@sfu.ca | w: wooya.me

**Comment by jnwang** [comment]
I prefer option 1 (i.e., either find another more beautiful theme or just use bokeh theme)
