### ISSUE TITLE
The documentation and tests is missing for create_report

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#236]
TODO:
- [ ] Add documentation for create report
- [ ] Fix the docstring for create_report (mode is not documented)
- [ ] Add tests for create report (codecov is down)

**Comment by eutialia** [comment]
I think doctoring for modes shouldn't be included, because the other modes are not complete. Doing this will cause confusion. We can add this part after all modes are fully implemented.

**Comment by dovahcrow** [comment]
Maybe just the modes that we already implemented?


Regards,
Weiyuan Wu

---
Weiyuan Wu | PhD Student
a: SFU-DB | 8888 University Dr. | Burnaby, BC, CA
e: youngw@sfu.ca | w: wooya.me

**Comment by eutialia** [comment]
Sounds good.
