### ISSUE TITLE
Replace the Bokeh layouts with our own html/js

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#237]
The Bokeh layouts do not provide the customizability needed for the auto-insights feature. Therefore, we will create the individual plots with Bokeh, and embed them into our own HTML. Preliminary ideas for the required changes are

1. An [icon added to the top right](https://github.com/sfu-db/dataprep/issues/203#issuecomment-650339139) of each plot for the auto-insights feature. It should not be present if there are no insights.
2. An icon for the how-to-guide similar to the icon for the auto-insights
3. Able to copy and paste the titles of the plots

Please give any other suggestions for this feature

**Comment by jnwang** [comment]
Looks good to me. This will be a super cool feature. Will it be a single function that allows the user to define what the layout looks like? That is, this function is similar to the Bokeh layout function with a couple of differences as you mentioned above.

**Comment by brandonlockhart** [comment]
@jnwang I was not planning for there to be any user control, just switch behind the scenes to using our own layout. Do you think the user should be able to define what the layout looks like?

**Comment by jnwang** [comment]
What I meant by "the user" is us. :) Since different plot functions (plot (df), plot(df, x), plot_diff(df1, df2)) require different layouts, this new function should allow us to define what layout looks like to meet these requirements.
