### ISSUE TITLE
ImportError: cannot import name 'future_set_exc_info'

### ISSUE THREAD

**Issue by alonnir** [sfu-db/dataprep#245]
Installed both locally and on a goog colab notebook.
Installation went fine. Python >=3.6

When trying to import `from dataprep.eda import plot` I'm getting:
```
ImportError: cannot import name 'future_set_exc_info'
```

**Comment by dovahcrow** [comment]
Hi @alonnir, thanks for the bug report! Can you have a try on restarting the Colab runtime right after installing DataPrep?

**Comment by alonnir** [comment]
Hey @dovahcrow thanks so much for the quick reply. That seems to do the trick! Thanks.

**Comment by dovahcrow** [comment]
@alonnir The problem is that Colab is using an old tornado.
