### ISSUE TITLE
Crowded and long labels problems for plot_missing() and plot_correlation()

### ISSUE THREAD

**Issue by dylanzxc** [sfu-db/dataprep#258]
Plot_corelation: The long label will push the graph to the corner. 
![image](https://user-images.githubusercontent.com/56427336/88085110-41297880-cb3a-11ea-9647-faa2ca963afc.png)
![image](https://user-images.githubusercontent.com/56427336/88085197-628a6480-cb3a-11ea-96ba-04865b846425.png)

Plot_missing: Similar Issue
![image](https://user-images.githubusercontent.com/56427336/88085279-7df56f80-cb3a-11ea-8ee5-ca0c10ca5295.png)
![image](https://user-images.githubusercontent.com/56427336/88085306-8483e700-cb3a-11ea-81be-98819669c66c.png)

**Comment by dylanzxc** [comment]
In addition, truncating names doesn't work here: 
![image](https://user-images.githubusercontent.com/56427336/88085406-a67d6980-cb3a-11ea-9539-80c9b1c66db3.png)

**Comment by brandonlockhart** [comment]
Fixed in #274
