### ISSUE TITLE
AttributeError: module 'tornado.ioloop' has no attribute '_Selectable'

### ISSUE THREAD

**Issue by THEMrinaal** [sfu-db/dataprep#263]
I was running Dataprep in my Kaggle Notebook and it throws an error mentioned in the header.
![rsz_dataprep](https://user-images.githubusercontent.com/29385581/88457369-9b785100-ce3a-11ea-98f9-4e235284e019.png)

**Comment by dovahcrow** [comment]
Hi @THEMrinaal Thanks for you bug report. This issue will be resolved by release 0.2.10. See related #218.
