### ISSUE TITLE
DataPrep report missing entities

### ISSUE THREAD

**Issue by meechos** [sfu-db/dataprep#278]
Dataprep report with `create_report(df)` is missing components with `Something Happened: 448893`.

Warnings produced as follows:
```python
/home/cdsw/.local/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:2003: RuntimeWarning: invalid value encountered in multiply
  lower_bound = _a * scale + loc
/home/cdsw/.local/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:2004: RuntimeWarning: invalid value encountered in multiply
  upper_bound = _b * scale + loc
/home/cdsw/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/cdsw/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/home/cdsw/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/cdsw/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]```
```
**Expected behavior**
A complete report.

**Screenshots**
![image](https://user-images.githubusercontent.com/429321/89667146-8c31e280-d8d3-11ea-830e-0e41d259bc8b.png)

**Desktop (please complete the following information):**
 - OS: Cloudera data science workbench
 - Browser: brave
 - Jupyter Lab
 - Platform Version  2.2.4 
 - Python Version 3.6.8
 - Dataprep Version 0.2.10

**Comment by brandonlockhart** [comment]
Hi @meechos, thanks for creating this issue! If this is a public dataset, can you let us know how to download it if possible? If not, I wonder if you can see any unusual characteristics in the columns that are failing, such as having a single unique value (which would result in stddev of 0), all missing values, or infinities? We've encountered some similar warnings with such columns and are currently fixing them.

**Comment by meechos** [comment]
Hi there. So, it was probably a couple of mistakes on my end, those being
- Running in Jupyter Lab, which is not yet supported
- Object dtypes for some variables in my dataframe

Works fine having corrected for the above. Many thanks
