### ISSUE TITLE
Breakdown plot's compute and render into multiple files

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#294]
Currently everything is crowded into a single file. It would be better to break it down into multiple files like univariate, bivariate, ...

**Comment by jinglinpeng** [comment]
I'm also considering this problem. My current idea is to push the compute and render logical into each type of figure. I.e., Histogram, Barchart, Wordcloud... For each type of figure, it has its own compute and render logical. The `plot` function first decide which figures to generate based on the input data type, then it calls the figure's compute and render approach. If we can handle in this way, adding new figures would be easier.
