### ISSUE TITLE
Support for numpy 1.19.1 possible?

### ISSUE THREAD

**Issue by ALee008** [sfu-db/dataprep#323]
Hey there,

I want to try out dataprep but am unwillung to downgrade my numpy version from currently 1.19.1 to 1.18.5. Are there plans for numpy 1.19.1 support? Will it 'break' dataprep if I manually upgrade numpy after dataprep installation?

Thank you and kind regards

ALee

**Comment by brandonlockhart** [comment]
Hi @ALee008. I manually upgraded to numpy 1.19.1 and dataprep did not 'break'. Please feel free to manually upgrade and create an issue if any problems arise. @dovahcrow can we upgrade numpy for the next release?

**Comment by ALee008** [comment]
Hey @brandonlockhart , 
thanks for your reply. Will upgrade manually and report as soon as I encounter problems.
