### ISSUE TITLE
DataPrep.Plot throwing Unreachable Error for a dataframe which has only strings for all columns

### ISSUE THREAD

**Issue by ssenathi** [sfu-db/dataprep#330]
My data set has 35 columns and all of them are string type . But looks like DataPrep is trying to detect whether it is nominal / categorical etc and if if couldn't find map, it is throwing error. I would expect it to default to Text . 

Could you let us know how to handle it error. Is there any parameter i can pass so that it default to Text if it couldn't determine whether it is date  / nominal / categorical values

--------------------------------------------------------------------------
UnreachableError                          Traceback (most recent call last)
<ipython-input-15-f105f6fd1e46> in <module>
----> 1 plot(df=df)

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/__init__.py in plot(df, x, y, z, bins, ngroups, largest, nsubgroups, timeunit, agg, sample_size, top_words, stopword, lemmatize, stem, value_range, yscale, tile_size, dtype)
    161         stem=stem,
    162         value_range=value_range,
--> 163         dtype=dtype,
    164     )
    165     figure = render(intermediate, yscale=yscale, tile_size=tile_size)

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/compute/__init__.py in compute(df, x, y, z, bins, ngroups, largest, nsubgroups, timeunit, agg, sample_size, top_words, stopword, lemmatize, stem, value_range, dtype)
     98 
     99     if not any((x, y, z)):
--> 100         return compute_overview(df, bins, ngroups, largest, timeunit, dtype)
    101 
    102     if sum(v is None for v in (x, y, z)) == 2:

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/compute/overview.py in compute_overview(df, bins, ngroups, largest, timeunit, dtype)
     74     for col in df.columns:
     75         srs = df[col]
---> 76         col_dtype = detect_dtype(srs, dtype)
     77         if is_dtype(col_dtype, Nominal()):
     78             ## if cfg.barchart_enable or cfg.any_insights("barchart"):

~/.local/lib/python3.6/site-packages/dataprep/eda/dtypes.py in detect_dtype(col, known_dtype)
    126     """
    127     if not known_dtype:
--> 128         return detect_without_known(col)
    129 
    130     if isinstance(known_dtype, dict):

~/.local/lib/python3.6/site-packages/dataprep/eda/dtypes.py in detect_without_known(col)
    173         return DateTime()
    174     else:
--> 175         raise UnreachableError
    176 
    177 

UnreachableError:

**Comment by dovahcrow** [comment]
Hi @ssenathi , thanks for the bug report! May I ask if you can provide us the dataset you use and the code to produce the error?

**Comment by ssenathi** [comment]
I am using AWS DataWrangler Library which creates Pandas DataFrame, but it has datatype like 'string', which i think DataPrep doesn't expect and kills itself.

Here is the Python code and also dtypes of the DataFrame

import pandas as pd
from dataprep.eda import plot
import awswrangler as wr
df = wr.athena.read_sql_query("SELECT 'Test' as TxtField, 20 as Num1Field, 30 as AnotherNumField" , database="default")

df
----------------------------------------------------------------

	txtfield	num1field	anothernumfield
0	Test	20	30
---------------------------------------------------------------------
df.dtypes
---------------------------------------------------------------------
txtfield           string
num1field           Int32
anothernumfield     Int32
dtype: object
-------------------------------------------------------------------
plot(df) 
-----------------------------------------------------------------------
throws the error

---------------------------------------------------------------------------
UnreachableError                          Traceback (most recent call last)
<ipython-input-16-9a29a1917b99> in <module>
----> 1 plot(df)

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/__init__.py in plot(df, x, y, z, bins, ngroups, largest, nsubgroups, timeunit, agg, sample_size, top_words, stopword, lemmatize, stem, value_range, yscale, tile_size, dtype)
    161         stem=stem,
    162         value_range=value_range,
--> 163         dtype=dtype,
    164     )
    165     figure = render(intermediate, yscale=yscale, tile_size=tile_size)

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/compute/__init__.py in compute(df, x, y, z, bins, ngroups, largest, nsubgroups, timeunit, agg, sample_size, top_words, stopword, lemmatize, stem, value_range, dtype)
     98 
     99     if not any((x, y, z)):
--> 100         return compute_overview(df, bins, ngroups, largest, timeunit, dtype)
    101 
    102     if sum(v is None for v in (x, y, z)) == 2:

~/.local/lib/python3.6/site-packages/dataprep/eda/distribution/compute/overview.py in compute_overview(df, bins, ngroups, largest, timeunit, dtype)
     74     for col in df.columns:
     75         srs = df[col]
---> 76         col_dtype = detect_dtype(srs, dtype)
     77         if is_dtype(col_dtype, Nominal()):
     78             ## if cfg.barchart_enable or cfg.any_insights("barchart"):

~/.local/lib/python3.6/site-packages/dataprep/eda/dtypes.py in detect_dtype(col, known_dtype)
    126     """
    127     if not known_dtype:
--> 128         return detect_without_known(col)
    129 
    130     if isinstance(known_dtype, dict):

~/.local/lib/python3.6/site-packages/dataprep/eda/dtypes.py in detect_without_known(col)
    173         return DateTime()
    174     else:
--> 175         raise UnreachableError
    176 
    177 

UnreachableError: 
​

**Comment by ssenathi** [comment]
Here is extremely simple one to re-produce the bug

import pandas as pd

df2 = pd.DataFrame(['1','2','3'], columns =["col1"],dtype='string')
df2.dtypes
plot(df2)

**Comment by jinglinpeng** [comment]
Hi @ssenathi , thanks for the bug report. This bug is due to string is not in the type detection component. We will fix it ASAP. For a quick fix, you could try to use object type:
```
import pandas as pd
from dataprep.eda import plot
df2 = pd.DataFrame(['1','2','3'], columns =["col1"],dtype='string')
df = df2.astype("object")
plot(df)
```

**Comment by yuzhenmao** [comment]
hi@ssenathi, it seems dask only support dtype '|S1' and 'object'. It doesn't support dtype 'string'. So maybe you need to replace `dtype='string'` to -- `dtype='S'` or `dtype='str'` or `dtype='object'`. And we will continue to fix this issue.

**Comment by ssenathi** [comment]
No problem. I can convert to object. Since your are using dask, is it
possible to connect to existing dask cluster ?. I want to profile 300 GB
dataset in s3. What do you think is the best solution?

**Comment by dovahcrow** [comment]
@ssenathi Since we don't do anything special to dask, I think you can connect to the dask cluster as normal. i.e. 

```python
from dask.distributed import Client
client = Client(cluster information)
```

And then you read the data from s3
```python
df = dd.read_csv("s3://...")
plot(df) / plot_missing(df) / plot_correlation(df)
```

**Comment by PedroMartinez4** [comment]
I encountered the same bug when feeding string columns to plot_diff()
