### ISSUE TITLE
regex to match country names in the ISO 3166 standard for clean_country()

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#347]
For `clean_country()` we need to identify countries in all of our supported formats. To start, and to complete this issue, we can create a regular expression to match countries in the "Country name" format of the ISO 3166 standard. More information on this can be found in the [API doc](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_country.ipynb).

**Comment by ryanwdale** [comment]
Here's my plan so far, looking to get people's opinions on this approach.

My plan is to use regexes from the country_converter project https://github.com/konstantinstadler/country_converter/blob/master/country_converter/country_data.tsv.

I'll adjust the regexes to make them slightly more strict. Some of the regexes use shortened versions of the country name which I'll change to the full name ie afghan -> afghanistan. The regexes also match an arbitrary string in between multi word names in some cases, I plan to change that to just a single space. For example if a country name is "Foo Bar", often times the country converter library uses the regex "foo.*bar" which I would change to "foo bar" (could also change it to "foo.?bar" which is also used a lot in the country_converter.).

Then regex.search will be used on these regexes to look for a match.

Also I plan to add an optional parameter `fuzzyDist` (default 0) like in this library https://www.rdocumentation.org/packages/rangeBuilder/versions/1.5/topics/standardizeCountry. If set to a non zero value the edit distance between the two strings will also be checked, if the edit distance is less than `fuzzyDist` it's a match.

Example regexes and country names:

"canada", "Canada"
"^(?!.*south).*georgia", "Georgia"
"channel island", "Channel Island"
"^(?!\.*north.\*).*ireland", "Ireland"

Example inputs and outputs:

"canada" -> "Canada"
"the country canada is nice" -> "Canada"
"cnada" -> "no match"
"cnada", `fuzzyDist` = 1 -> "Canada"
"channel island" -> "Channel Island"
"channel foo island" -> "no match"
"foo georgia bar" -> "Georgia"
"south georgia" -> "no match" (South Georgia is an island unrelated to Georgia the country)
"   ireland   " -> "Ireland"
"northern ireland" -> "no match" (Northern Ireland is part of the United Kingdom)


Any input is greatly appreciated!

**Comment by jnwang** [comment]
Great job, @ryanwdale ! The design looks excellent. I am particularly impressed by the fuzzyDist idea. 

I have two comments on clean functions in general.

1. Should we handle "the country canada is nice" and  " Ireland "? We decided not to do in the `clean_long_lat `function (see #310), but it seems that it's time to rethink this decision. 

2. There could be many duplicate countries in a column. To save time, should we apply the clean operator to each unique country? This is a common problem for all clean functions.

**Comment by brandonlockhart** [comment]
Yes, great job Ryan! I like this design. My thoughts on Jiannan's comments:

For 1., I agree that we should rethink this decision. A question for `validate_country` is should "the country canada is nice" validate to True? If not, we would need to define a set of strings we would recognize as being a valid country, eg including "China", "PRC", "People's Republic of China", "The People's Republic of China", "People's Rep. of China", ..., which could be tedious to create. But I like Ryan's proposed "search" approach for `clean_country` since I think it will be more efficient and appropriate for most cases. 

For 2., I like this idea.
