### ISSUE TITLE
clean_url design

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#358]

**Comment by peterirani** [comment]
```
def clean_url(
        df : Union[pd.DataFrame, dd.DataFrame],
        column : str,
        inplace : bool = False,
        complex_text : bool = False,
        query_param = "string or list of strings"
    ) -> Any:
```

The input parameters are as follows:
1) df -> the input dataframe (dask or pandas datatype)
2) column -> Name of the column (string datatype)
3) inplace -> do we want to replace the existing column of urls with the cleaned urls. By default it a new column will be formed (Boolean datatype).
4) complex_text -> The the column contain texts other than `urls`. For example  "this is an example of https://www.facebook.com?auth=93487skfsdf"
5) query_params -> "string or list of strings" , we will parse the the url columns and form a columns with those query params as the column heads. For example in the example in point number 4, if we enter `query_params = "auth"` this will create a new column with the value of `93487skfsdf`

Other ideas include : 
- remove only certain query params from the urls.

**Comment by brandonlockhart** [comment]
Great job, Peter! Should we change the parameter name `complex_text` to `strict` to be consistent https://github.com/sfu-db/dataprep/issues/357#issuecomment-698122315? If I understand correctly, they do the same thing.

**Comment by peterirani** [comment]
Thanks Brandon! Yes `strict` sounds much better than `complex_text`. 
So by default `strict` will be set to `True`, when it set to `True` it would mean that we can expect the column to **only** have urls in it. When it is set to `False` it will have to parse some text to extract the urls. Please let me know if this convention sounds okay or should I reverse it?

**Comment by yxie66** [comment]
Thank you Peter, it looks great to me. Based on my opinion your understanding of `strict` is correct, I wonder how Brandon think about it.

By the way, according to the discussion in last week, should we implement something to let user remove some parameters from urls? If yes, should we do that using `query_params` or we need to create a new parameter? My opinion is that we can create a new parameter, otherwise the syntax of values for `query_params` will become more complicated.

**Comment by peterirani** [comment]
Hi Yi, yes creating a new parameter to remove a particular parameter would be great. For example remove the `auth` tokens from the urls.

**Comment by brandonlockhart** [comment]
> So by default `strict` will be set to `True`

In `clean_country` (https://github.com/sfu-db/dataprep/issues/357#issuecomment-698190244, https://github.com/sfu-db/dataprep/issues/357#issuecomment-698669755) we said the default would be `False`. I think we should have a good reason why we have different default values between these functions; my preference is to have default `False` in both functions. It might be good to discuss this parameter and its default values in our meeting.

I'm unclear about what "some parameters" are here:

> should we implement something to let user remove some parameters from urls?

and the difference between removing these parameters and the task completed by `query_params`. Can @yxie66 or @peterirani please list what the "some parameters" are if possible, and elaborate a little about why we need two parameters? We can discuss this in our meeting tomorrow.
