### ISSUE TITLE
Connector: Refine .info()

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/dataprep#364]
- Understand thoroughly the current approach to generate output for .info() function
- Identify the inadequacy of the current approach
- propose an improvement solution
- implement the solution

**Comment by nick-zrymiak** [comment]
On it!

**Comment by dovahcrow** [comment]
@nick-zrymiak @peiwangdb is this finished?

**Comment by nick-zrymiak** [comment]
> @nick-zrymiak @peiwangdb is this finished?

Yes!
