### ISSUE TITLE
enrich text analysis: design

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#368]

**Comment by Waterpine** [comment]
@jinglinpeng Do you have any comments? https://docs.google.com/document/d/1EQUBEgU_khNl51Z2FPv_4rUGziiZz8fYzXKvqsVXGFU/edit?usp=sharing

**Comment by jinglinpeng** [comment]
@Waterpine  Good job! Do you have any idea of how those plots can be integrated into `plot` function? Besides, I'm not sure the meaning of some plots, could you introduce them in the meeting?

**Comment by Waterpine** [comment]
@jinglinpeng I agree with you. I should show some demo of these tools to help members to understand the meaning of some plots. The thing I want to discuss is whether we have to integrate NLP processing into our library and how to integrate text scatter plot into plot function.
