### ISSUE TITLE
Feature Proposal: clean_url functionality in the clean module

### ISSUE THREAD

**Issue by peterirani** [sfu-db/dataprep#390]
## Summary
Implement clean_url functionality to clean and parse url in a dataset.

## Design-level Explanation Actions
- [x] Create a clean_url function signature that takes into consideration the parsing the url, cleaning the url, removing authentication params and has inplace / split functionality.
- [x] Create a validate url function to parse a column or a value and check if it is url or not.

## Design-level Explanation
The proposed `clean_url` function signature is given below:

```python
def clean_url(
    df : Union[pd.DataFrame, dd.DataFrame],
    column : str,
    inplace : bool = False,
    split : bool = False,
    remove_auth : Union[bool, List[str]] = False,
    report : bool = True
    ) -> Union[pd.DataFrame, dd.DataFrame]:

    """
    This function cleans url
    Parameters
    ----------
    df
        pandas or Dask DataFrame
    column
        column name
    inplace
        If True, delete the given column with dirty data, else, create a new
        column with cleaned data.
    split
        If True, split a column containing individual columns representing `scheme`, `host`, `path`, etc.
    remove_auth
        Can be bool or a list of strings representing the names of authentication tokens to be removed.
    report
        Generates a short report on how many rows were cleaned, and how many were left untouched
    """
```

The proposed `validate_url` signature is given below:
```python
def validate_url(
    x : Union[str, pd.Series] 
) -> Union[bool, pd.Series] :
    """
    This function validates url
    Parameters
    ----------
    x
        pandas Series of urls or url instance
    """

```

### Ability to split or get compressed data
- The `clean_url` function should be able to parse the url and extract the important parameters from the url, with the option to split it into multiple columns or get all the details as in one column as a key-value pair.

### Ability to remove authentication params via multiple ways
- Also we have given the users the ability to remove auth_tokens from the urls, this is done via the `remove_auth` param. This can either be a `bool` value or a `list` of strings representation names of query that the user wants to remove from the url. 
    - If a `remove_auth` is set to the bool value `True`. The url is parsed and the tokens are removed based upon a default list of authentication tokens  (`AUTH_VALUES`)which are given below: 
   -  If user specifies a list of auth key names to be removed, then we combine the default `AUTH_VALUES` with the user defined  list and remove the auth parmas based on the Union of the two lists.
```
    AUTH_VALUES = {
        "access_token",
       "auth_key",
       "auth",
       "password",
       "username",
       "login",
       "token"
   }
```

### Ability to accomondate duplicate query names
- For the queries params, we can have duplicate query names with same or different values, for e.g:
`https://www.defaultdomain.com/store/loc=123&time=123&loc=234&loc=123` in such a situation we woud like to store the multiple values of `loc` as a list to accomodate more than one value . Hence for the given example the queries dictionary would look like`queries = {"loc" : ["123", "234", "123"],  "time"=123}

### Functionality to extract query params

- The alternate design would not only allow the user to remove any query based but all also extract the values of the queries. For example if we have a list of urls containing all the product names from a ecommerce website and the query name is `product` we can parse the url column and make a new column called product. Eg. `https://www.amazon.ca/electronics/product=acer-15-16gb` or `https://www.amazon.ca/food/product=cookies-1kg`

And column would look like 

|Product|
|--------|
|acer-15-16gb|
|cookies-1kg|

## Prior Art

The open WIP can be found here #388 

## Future Possibilities

Implement the extract queries from `url` explained in the rational and alternative section 

## Additional Tasks

- [ ] This task is put into a correct pipeline (Development Backlog or In Progress).
- [ ] The label of this task is setting correctly.
- [ ] The issue is assigned to the correct person.
- [ ] The issue is linked to related Epic.

- [ ] The documentation is changed accordingly.
- [ ] Tests are added accordingly.

**Comment by yxie66** [comment]
Good job Peter!
