### ISSUE TITLE
Feature Proposal: clean_country functionality in the clean module

### ISSUE THREAD

**Issue by ryanwdale** [sfu-db/dataprep#392]
## Summary

Implement a function clean_country() that cleans messy country names and converts them between [ISO 3166 country codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes). 

## Design-level Explanation Actions

- [x] Investigate other libraries to figure out whether their solutions work for our use case.
- [x] Test different ideas for matching country names.
- [x] Discuss solutions with the team to determine everyone's preferred approach. #357 

## Design-level Explanation

Countries can be converted to/from the following formats:
     1. "name": the country name,
     2. "official": the official state name,
     3. "alpha-2": two letter abbreviation,
     4. "alpha-3": three letter abbreviation,
     5. "numeric": numeric code

The `input_format` can also be "auto", in this case the input format is inferred based on the input.

Proposed function signature for clean_country():

```python3
def clean_country(
    df: Union[pd.DataFrame, dd.DataFrame],
    column: str,
    input_format: str = "auto",
    output_format: str = "name",
    fuzzy_dist: int = 0,
    strict: bool = False,
    inplace: bool = False,
    report: bool = True,
    errors: str = "coerce",
) -> pd.DataFrame:
    """
    This function cleans countries

    Parameters
    ----------
    df
        pandas or Dask DataFrame
    column
        column name containing messy country data
    input_format
        the ISO 3166 input format of the country:
        "auto" (infers the input format), country name ("name"),
        official state name ("official"), alpha-2 code ("alpha-2"),
        alpha-3 code ("alpha-3"), numeric code ("numeric")
    output_format
        the desired format of the country:
        country name ("name"), official state name ("official"), alpha-2 code ("alpha-2"),
        alpha-3 code ("alpha-3"), numeric code ("numeric")
    fuzzy_dist
        The maximum edit distance (number of single character insertions, deletions
        or substitutions required to change one word into the other) between a country value
        and input that will count as a match.
    strict
        If True, matching for input formats "name" and "official" are done by looking
        for a direct match, if False, matching is done by searching the input for a
        regex match
    inplace
        If True, delete the given column with dirty data, else, create a new
        column with cleaned data.
    report
        If True, output the summary report. Otherwise, no report is outputted.
    errors {‘ignore’, ‘raise’, ‘coerce’}, default 'coerce'
        * If ‘raise’, then invalid parsing will raise an exception.
        * If ‘coerce’, then invalid parsing will be set as NaN.
        * If ‘ignore’, then invalid parsing will return the input.
    """
```

Proposed function signature for validate_country():
```python3
def validate_country(
    x: Union[str, int, pd.Series], input_format: str, strict: bool = True
) -> Union[bool, pd.Series]:
    """
    This function validates countries

    Parameters
    ----------
    x
        pandas Series of countries or str/int country value
    input_format
        the ISO 3166 input format of the country:
        "auto" (infers the input format), country name ("name"),
        official state name ("official"), alpha-2 code ("alpha-2"),
        alpha-3 code ("alpha-3"), numeric code ("numeric")
    strict
        If True, matching for input formats "name" and "official" are done by
        looking for a direct match, if False, matching is done by searching
        the input for a regex match
    """
```

## Implementation-level Explanation

#382 This PR has the current implementation.

Regexes are taken from the [country_converter](https://github.com/konstantinstadler/country_converter/blob/master/country_converter/country_data.tsv.) project. The regexes are then adjusted to be made more strict. Some of the regexes use shortened versions of the country name which I'll change to the full name ie afghan -> afghanistan. They also match an arbitrary string in between multi word names in some cases, I plan to change that to just a single space.

### Matching "name" and "official" Formats
When `strict = False` then `re.search` is used on the input string. So if a regex match is contained within the input string then the input is counted as a valid country and it will be converted/validated accordingly. When `strict = True` then the input must match the ISO 3166 country code format exactly (after stripping whitespace) to be cleaned or validated.

### Matching "alpha-2", "alpha-3" and "numeric" Formats

For these formats the input must match the ISO 3166 country code format exactly (after stripping whitespace) to be cleaned or validated.

### Fuzzy Matching

When the input format is "name" or "official" a match is found if a country has an edit distance <= `fuzzy_dist` with a string that contains a match with one of the country regexes. The match with the minimum edit distance is returned. This is done using the [regex](https://pypi.org/project/regex/) library. 

When the input format is "alpha-2", "alpha-3" or "numeric" then the edit distance is computed with every country value and the minimum one is taken if it is <= `fuzzy_dist`. I plan to run benchmarks and optimize this with the code and paper provided by Jiannan in a future PR.
 

## Rationale and Alternatives

The current design provides a good amount of flexibility to the user allowing for more or less inputs to be matched with the `strict` and `fuzzy_dist` parameters.

The regexes could be rewritten to be made more or less strict, the current approach seems to have a good balance between matching most inputs that are countries while avoiding matching inputs that may not be countries.

The fuzzy matching approach using regexes could be changed to check the edit distance with the respective country values. This could reduce functionality slightly but would improve performance, I plan on reconsidering this while doing benchmarks and optimizing the code.

## Prior Art

[country_converter](https://github.com/konstantinstadler/country_converter) 
[pycountry](https://github.com/flyingcircusio/pycountry) Uses a very strict approach, inputs must match ISO 3166 country code exactly.
[standardizeCountry](https://www.rdocumentation.org/packages/rangeBuilder/versions/1.5/topics/standardizeCountry) R library with fuzzyDist parameter.

## Future Possibilities

The country_converter library has some other features that seem useful, for example filtering countries that are in the UN.

## Implementation-level Actions

- [x] create regexes for matching countries
- [x] implement according to design discussed in #357  

## Additional Tasks

- [x] This task is put into a correct pipeline (Development Backlog or In Progress).
- [x] The label of this task is setting correctly.
- [x] The issue is assigned to the correct person.
- [x] The issue is linked to related Epic.

- [ ] The documentation is changed accordingly.
- [ ] Tests are added accordingly.

**Comment by brandonlockhart** [comment]
Very nicely written, Ryan! For fuzzy matching with the "alpha-2", "alpha-3" and "numeric" formats, I think there can be many matches. For example,
![Screen Shot 2020-10-17 at 10 14 43 PM](https://user-images.githubusercontent.com/25874021/96359317-5cb70780-10c6-11eb-8577-6ae11f3989af.png)
but "use" also matches "usa".
I don't think we need to support fuzzy matching for these formats, but this is just my opinion.

**Comment by ryanwdale** [comment]
Thanks Brandon!

> I don't think we need to support fuzzy matching for these formats

I think that's a good idea, the behaviour you described makes the feature pretty useless.
