### ISSUE TITLE
Connector: remove dependency on requests library

### ISSUE THREAD

**Issue by peiwangdb** [sfu-db/dataprep#397]
Remove the installation dependency on requests library and modify the code accordingly.
Example: chang:

import requests
requests.get("www.python.org").json()

to:

import http.client
import json
conn = http.client.HTTPSConnection("www.python.org")
conn.request("GET", "/")
r1 = conn.getresponse()
json.loads(r1.read())

**Comment by dovahcrow** [comment]
Close in favor of #396
