### ISSUE TITLE
plot(df, x): histogram shows incorrect values

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#40]
When running plot(df, 'year' 31) on the example dataset (suicide-rate.csv), I got the following histogram, which shows are **2015: 936** and *2016: *904**. However, the correct values should be **2015: 744** and **2016: 160**.

<img width="580" alt="Screen Shot 2019-12-18 at 11 21 31 PM" src="https://user-images.githubusercontent.com/1028970/71153347-c12ae100-21ed-11ea-8be4-17aaa3451a66.png">

**Comment by brandonlockhart** [comment]
The counts are correct. We are using the dask array histogram library function to compute the histogram which is a blocked variant of the numpy histogram https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html#numpy.histogram. The bins in this example case are [1985, 1986), [1986, 1987), ..., [2014, 2015), **[2015, 2016]**; a square bracket denotes inclusion in the interval, a round bracket denotes exclusion. @jnwang please let me know if you still think there is a problem after this explanation on binning.

@jnwang I think what you were expecting is effectively an ordered bar chart. This raises some points:
1. Where are we telling the user the calculations behind the plots (e.g. the binning bounds for a histogram, whiskers and outliers in a box plot, etc.)
2. Is there a problem (can it be confusing) to show a histogram of discrete values (as in this case).
3. Do we need to think specifically about presenting time series data.

**Comment by jnwang** [comment]
Thanks Brandon for your explanation. I have no concern about this bug, but after changing #bins from 31 to 32, I found two other issues. 

I feel like the tooltip seems to have some issues. Please take a look at the following plot. The first bar should be [1985, 1986), but the tooltip shows [1985, 1986]. Another thing is about the xtics. For this example, why the xtics shows 1985.969 rather than 1986?

<img width="658" alt="Screen Shot 2019-12-19 at 10 15 16 PM" src="https://user-images.githubusercontent.com/1028970/71234431-9e600180-22ad-11ea-93f0-0555c344511d.png">

**Comment by brandonlockhart** [comment]
I've fixed the tooltip. @jnwang  I don't understand what is wrong with the xtics. In your above example, 32 equal-width bins are created between 1985 and 2016, which are correctly denoted in the xtics. I don't understand why you are expecting 1986 rather than 1985.969.

**Comment by jnwang** [comment]
Sorry that I did not describe my question clearly. 

What I was confused about is that tooltip and xtics are inconsistent, where the tooltip shows [1985, 1986] while the xtics shows [1985, 1985.969]. 

The plot below shows a more clear example, where the tooltip shows [2001, 2002] while the xtics shows [2001.469, 2002.438]

<img width="690" alt="Screen Shot 2019-12-22 at 11 29 18 AM" src="https://user-images.githubusercontent.com/1028970/71326373-a3d86a00-24ae-11ea-9ec3-4ddcb526c353.png">

Maybe we can address this issue in #38

**Comment by brandonlockhart** [comment]
Thank you for clarifying. I think the tooltip was just rounding. This is how it looks after fixing the bin intervals in the tooltip.
![image](https://user-images.githubusercontent.com/25874021/71326619-2878b780-24b2-11ea-8099-a9dbad476d85.png)

**Comment by jnwang** [comment]
Now it looks consistent. Thanks!
