### ISSUE TITLE
plot(df, x, y): ngroups does not work

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#41]
I would like to increase the number of groups in the box plot of plot(df, "suicides", "country"), but found that setting ngroups = 20 does not work (see below). 

<img width="627" alt="Screen Shot 2019-12-20 at 12 58 03 PM" src="https://user-images.githubusercontent.com/1028970/71293016-03a50880-2329-11ea-8ec4-6fd3d093ca50.png">

**Comment by brandonlockhart** [comment]
This bug has been fixed:
![image](https://user-images.githubusercontent.com/25874021/71372444-435a3300-2569-11ea-8100-a56d35f4b1ef.png)
Two follow up questions:
1. Currently we only let the user see the largest groups, should we let the user specify to see the smallest groups as they currently can with a bar chart?
2. Should this plot also get wider if the number of groups is large as requested in #42 ?

We can perhaps consider these points in #42 .

**Comment by jnwang** [comment]
1. I think it's a good idea to let the user specify to see the smallest groups.
2. Yes. This can be considered in #42.
