### ISSUE TITLE
create_report on a DataFrame with a datetime64[ns] column results in a uncaught exception

### ISSUE THREAD

**Issue by dgonzo** [sfu-db/dataprep#412]
**Describe the bug**
Calling `create_report` on a DataFrame with a datetime64[ns] column results in a uncaught exception: `UnboundLocalError: local variable 'rndrd' referenced before assignment`

**To Reproduce**
1. Example dataset
```python
import random
import pandas as pd
from dataprep import eda

weeks = pd.date_range(start='2020-10-01', end='2020-11-04', freq='W')
week_of = [random.choice(weeks) for n in range(random.randint(0, 1_000))]
some_counts = [c for c in range(len(week_of))]
td = pd.DataFrame({'week_of': week_of, 'some_counts': some_counts})
```
2. Create report
```python
report = eda.create_report(td, title='Report with datetime')
```
3. See error
```python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-10-c4d17e3c9e92> in <module>
----> 1 report = eda.create_report(dist_df, title="Distribution Report")

/usr/local/lib/python3.8/site-packages/dataprep/eda/create_report/__init__.py in create_report(df, title, mode, progress)
     52         "resources": INLINE.render(),
     53         "title": title,
---> 54         "components": format_report(df, mode, progress),
     55     }
     56     template_base = ENV_LOADER.get_template("base.html")

/usr/local/lib/python3.8/site-packages/dataprep/eda/create_report/formatter.py in format_report(df, mode, progress)
     61         df = string_dtype_to_object(df)
     62         if mode == "basic":
---> 63             comps = format_basic(df)
     64         # elif mode == "full":
     65         #     comps = format_full(df)

/usr/local/lib/python3.8/site-packages/dataprep/eda/create_report/formatter.py in format_basic(df)
    121             )
    122         figs: List[Figure] = []
--> 123         for tab in rndrd:
    124             try:
    125                 fig = tab.children[0]

UnboundLocalError: local variable 'rndrd' referenced before assignment
```

**Expected behavior**
I believe in this case the desired behavior is that the dates be treated as categorical and a histogram produced.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Platform: Python script
 - Platform Version: 3.8
 - Python Version: 3.8
 - Dataprep Version: '0.2.14'

**Comment by brandonlockhart** [comment]
Hi @dgonzo, thanks for creating this issue. This error has been fixed in PR #438 which will be included in the next release.

![Screen Shot 2020-11-29 at 7 50 20 PM](https://user-images.githubusercontent.com/25874021/100568192-5b5d2b00-327f-11eb-86b1-89b97502d91f.png)


By the way, we're planning on improving our support for time series analysis in the near future; e.g., adding more plots and stats. Please let us know if you have any suggestions.
