### ISSUE TITLE
plot(df, x, y): make it possible and easy for users to set ngroups

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#42]
When running plot(df, "country", "generation"), I got the following plots. It seems that it is impossible to adjust ngroups (i.e., top 5, top 20, top 70) for each plot. 

<img width="967" alt="Screen Shot 2019-12-20 at 1 13 06 PM" src="https://user-images.githubusercontent.com/1028970/71293952-e9205e80-232b-11ea-928b-a3abde12f0a3.png">
<img width="1053" alt="Screen Shot 2019-12-20 at 1 13 14 PM" src="https://user-images.githubusercontent.com/1028970/71293953-e9205e80-232b-11ea-8158-2ace482495c0.png">
<img width="1029" alt="Screen Shot 2019-12-20 at 1 13 26 PM" src="https://user-images.githubusercontent.com/1028970/71293955-e9205e80-232b-11ea-87c6-8cc240697b9f.png">

To make it easy to set ngroups, I have one proposal. 

- First, we make the three plots have the same ngroups by default (e.g., ngroups = 10). 
- Second, if a user wants to change ngroups, she only needs to change one parameter and then it will be applied to all three plots.
- Third, if ngroups is very large, then we should increase the plot width/height automatically so that a user can view the whole plot by scrolling the vertical and horizontal bars. See the plot below for an example. 

<img width="843" alt="Screen Shot 2019-12-20 at 1 25 06 PM" src="https://user-images.githubusercontent.com/1028970/71294163-7ebbee00-232c-11ea-8533-b1ce093484b7.png">

**Comment by brandonlockhart** [comment]
There is another parameter I'm using _nsubgroups_ that specifies in the above example how many groups from _generation_ are shown (whereas _ngroups_ specifies how many groups from _country_). We could give the user control of nsubgroups and set it to 5 by default which would give the following (with default ngroups=10):
![image](https://user-images.githubusercontent.com/25874021/71373489-3428b480-256c-11ea-991b-a18fb1e3fa4c.png)
![image](https://user-images.githubusercontent.com/25874021/71373497-3985ff00-256c-11ea-947b-cde9a07b370c.png)
![image](https://user-images.githubusercontent.com/25874021/71373502-3f7be000-256c-11ea-9f66-73fb7fafacc8.png)

**Comment by brandonlockhart** [comment]
The user can now specify ngroups and nsubgroups, and the plots will get wider appropriately.
![image](https://user-images.githubusercontent.com/25874021/71536617-edb5bb80-28c5-11ea-8136-9805ba4ebf4c.png)
![image](https://user-images.githubusercontent.com/25874021/71536645-6583e600-28c6-11ea-9dd8-2bf4777cb800.png)
![image](https://user-images.githubusercontent.com/25874021/71536674-c1e70580-28c6-11ea-9366-c050b352ea9d.png)

**Comment by brandonlockhart** [comment]
@jnwang can we close this issue?
