### ISSUE TITLE
plot_missing: documentation for num_bins and num_cols

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#43]
Please check below a screenshot of the documentation for [plot_missing](https://sfu-db.github.io/dataprep/dataprep.eda.html#dataprep.eda.plot_missing). 

<img width="949" alt="Screen Shot 2019-12-20 at 1 42 37 PM" src="https://user-images.githubusercontent.com/1028970/71294878-c479b600-232e-11ea-83cc-a6e5dfd2426f.png">

There are a few issues:

1. It should be "num_bins" rather than "bins_num". The description ("The number of rows in the figure") is also a bit confusing.
2. In [plot(df)](https://sfu-db.github.io/dataprep/dataprep.eda.html#dataprep.eda.plot), this parameter is called bins. Please work with @brandonlockhart  and make it consistent. I would suggest calling it **bins**, which is consistent with [pandas.dataframe.hist](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.hist.htmlpandas.DataFrame.hist.html). 
3. Maybe it's better to use ncols instead of num_cols. This is because that in [plot(df)](https://sfu-db.github.io/dataprep/dataprep.eda.html#dataprep.eda.plot), there is a parameter called **ngroups**, which is short for num_groups.

**Comment by Waterpine** [comment]
@jnwang @dovahcrow I agree with you, I will fix this bug after young and jinglin merge other PR which could avoid unnecessary conflict.

**Comment by dovahcrow** [comment]
Blocked by #57

**Comment by jinglinpeng** [comment]
Could you please a look at this issue? @Waterpine

**Comment by Waterpine** [comment]
Sorry, I forgot to fix this bug. I will fix it tomorrow. @jinglinpeng
