### ISSUE TITLE
plot_missing(df): bugs in tooltips

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#44]
I got a dataset collected from Yelp using the data_connector API. The dataset has 20 rows. Below shows the first 10 values in the **address3** column.

<img width="273" alt="Screen Shot 2019-12-20 at 2 51 37 PM" src="https://user-images.githubusercontent.com/1028970/71297585-f09a3480-2338-11ea-8c98-853cc79a80ea.png">

**Bug 1.** Please check the tooltip below. 

- missing% is larger than 100%?
- loc should be 5 rather than 4~5.

<img width="616" alt="Screen Shot 2019-12-20 at 2 52 44 PM" src="https://user-images.githubusercontent.com/1028970/71297547-c3e61d00-2338-11ea-87b8-d9f02bc61df4.png">

**Bug 2.** Please check the tooltip below.

- Should the location of the first row 1 or 0? In Pandas Dataframe, iloc starts from 0. 

<img width="586" alt="Screen Shot 2019-12-20 at 3 02 55 PM" src="https://user-images.githubusercontent.com/1028970/71297808-db71d580-2339-11ea-8cab-7553c0a32df7.png">

**Bug 3.** Should we consider empty strings as missing values? If so, the address3 column should have many more missing values.

**Comment by dovahcrow** [comment]
For bug 3, I think we should keep the same "missing" semantic as pandas, as well as SQL. In SQL NULL is not same as empty string. And in pandas:
```
pd.isnull('')
False
```

For bug 3, a user can simply replace all the empty strings with None.

**Comment by jnwang** [comment]
I agree!
