### ISSUE TITLE
Feature Proposal: clean_headers functionality in clean module

### ISSUE THREAD

**Issue by atol** [sfu-db/dataprep#447]
## Summary

Implement `clean_headers()` function to clean headers / column names in a DataFrame.

## Design-level Explanation Actions

- [x] Investigate prior art solutions for cleaning column names.
- [X] Consider which parameters to support.
- [X] Consider which target string cases to support.

## Design-level Explanation

Function signature for `clean_headers()`:

``` python
def clean_headers(
    df: Union[pd.DataFrame, dd.DataFrame],
    case: str = "snake",
    replace: Optional[Dict[str, str]] = None,
    remove_accents: bool = True,
    report: bool = True,
) -> pd.DataFrame:
    """
    Function to clean column headers (column names).

    Read more in the :ref:`User Guide <clean_headers_user_guide>`.

    Parameters
    ----------
    df
        Dataframe from which column names are to be cleaned.
    case
        The desired case style of the column name.
            - 'snake': 'column_name'
            - 'kebab': 'column-name'
            - 'camel': 'columnName'
            - 'pascal': 'ColumnName'
            - 'const': 'COLUMN_NAME'
            - 'sentence': 'Column name'
            - 'title': 'Column Name'
            - 'lower': 'column name'
            - 'upper': 'COLUMN NAME'

        (default: 'snake')
    replace
        Values to replace in the column names.
            - {'old_value': 'new_value'}

        (default: None)
    remove_accents
        If True, strip accents from the column names.

        (default: True)
    report
        If True, output the summary report. Otherwise, no report is outputted.

        (default: True)

    Examples
    --------
    Clean column names by converting the names to camel case style, removing accents,
    and correcting a mispelling.

    >>> df = pd.DataFrame({'FirstNom': ['Philip', 'Turanga'], 'lastName': ['Fry', 'Leela'], \
'Téléphone': ['555-234-5678', '(604) 111-2335']})
    >>> clean_headers(df, case='camel', replace={'Nom': 'Name'})
    Column Headers Cleaning Report:
        2 values cleaned (66.67%)
      firstName lastName       telephone
    0    Philip      Fry    555-234-5678
    1   Turanga    Leela  (604) 111-2335
    """
```

### Convert Case

`case` specifies which case style to convert the column names to. The default is `snake_case`. Supported case styles include:

``` python
case_styles = {
        "snake",  # column_name
        "kebab",  # column-name
        "camel",  # columnName
        "pascal",  # ColumnName
        "const",  # COLUMN_NAME
        "sentence",  # Column name
        "title",  # Column Name
        "lower",  # column name
        "upper",  # COLUMN NAME
}
```

### Replace Values

Users can specify values to be replaced in the column names by passing in a dictionary to `replace`.
``` python
clean_headers(df, case="kebab", replace={"#": "number", "%": "percent", "cell": "mobile"})
```

### Remove Accents
If `remove_accents` is set to `True` (default), accents will be stripped from the column names.

### Rename Duplicate Column Names

Column names duplicated as a result of calling `clean_headers()` are automatically renamed by appending a number to the end.

For example:

| Monthly Sales | (Monthly) Sales |
| ------------- | ------------- |
| 180 | 400 |
| 500 | 675 |

``` python
clean_headers(df)
```

| monthly_sales | monthly_sales_1 |
| ------------- | ------------- |
| 180 | 400 |
| 500 | 675 |

The suffix used to append the number is inferred from the case style, e.g. `_` for `snake` or `const`, `-` for `kebab` and a space for `lower` or `upper`.

``` python
clean_headers(df, case="kebab")
```

| monthly-sales | monthly-sales-1 |
| ------------- | ------------- |
| 180 | 400 |
| 500 | 675 |

## Rational and Alternatives

`remove_accents` uses [unicodedata](https://docs.python.org/3/library/unicodedata.html), which simply strips accents from the column name. A more accurate result may be obtained by using [unidecode](https://pypi.org/project/Unidecode/), which transliterates the Unicode string into the closest possible ASCII representation. However, the advantage of using `unicodedata` is that it is part of the Python standard library.

## Prior Art

[janitor](http://sfirke.github.io/janitor/index.html): R package for cleaning data, specifically the `clean_names()` function documented [here](http://sfirke.github.io/janitor/articles/janitor.html#clean-data-frame-names-with-clean_names).
[pyjanitor](https://github.com/ericmjl/pyjanitor): Python implementation of `janitor` with a similar `clean_names()` function documented [here](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.clean_names.html?highlight=clean_name#janitor.clean_names).
[stringcase](https://pypi.org/project/stringcase/): Python package for converting string cases between camel case, pascal case, snake case, etc.
[unidecode](https://pypi.org/project/Unidecode/): Python package for mapping a Unicode string to ASCII characters.
[unicodedata](https://docs.python.org/3/library/unicodedata.html): Python package for normalizing Unicode strings.
[gensim.utils.deaccent](https://radimrehurek.com/gensim/utils.html#gensim.utils.deaccent): Gensim library function for removing letter accents from a given string.

## Implementation-level Actions

- [X] Implement `convert_case()` to convert the column name to different string cases.
- [X] Implement removal of accents from the column name.
- [X] Implement replacement of "%" and "#" symbols with words.
- [X] Implement renaming of duplicate column names.

## Additional Tasks

- [X] This task is put into a correct pipeline (Development Backlog or In Progress).
- [X] The label of this task is set correctly.
- [X] The issue is assigned to the correct person.
- [ ] The issue is linked to a related Epic.

- [X] The documentation is changed accordingly.
- [X] Tests are added accordingly.

**Comment by brandonlockhart** [comment]
Nice job, @atol! This design looks great to me. I would just propose one more case style that I've seen on occasion: snake case with all capital letters, e.g., `FIRST_NAME`. I think this case can be called `upper_snake` or [`screaming_snake`](https://rdrr.io/cran/snakecase/man/to_any_case.html), but feel free to suggest another name that you prefer.

**Comment by atol** [comment]
Thanks for the input, @brandonlockhart! `upper_snake` seems preferable to `screaming_snake` since the latter sounds a little frightening 😄 But I've also seen it referred to as `const_case`, which has the benefit of keeping with the one-word naming so I'm leaning towards that.

As an aside, it seems that `kebab-case` is more popular than `spinal-case` so I'll likely change to that.

**Comment by brandonlockhart** [comment]
One more thing, I think the default case should be `snake` rather than `lower` so that the words are not lost.

**Comment by atol** [comment]
Good point, I agree!
