### ISSUE TITLE
DataPrep.Clean Spring Semester Plan

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#451]
Next semester, we would like to implement more APIs, make our existing functions performant, and acquire real-world users. We are planning on completing the following tasks:

### New Cleaning Functions

* `clean_ml()` - transform a dataframe into a format suitable for ML ([tentative design](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_ml.ipynb))
* `clean_text()` - clean a column containing text data ([tentative design](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_text.ipynb))
* `clean_duplication()` - standardize different representations of the same string ([tentative design](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_duplication.ipynb)). This function will use clustering to identify the different representations, and have a front-end GUI to interactively standardize the strings.
* `clean_df()` - clean a dataframe. We would like to identify whether there is a set of operations that would be useful for cleaning and standardizing a full dataframe. For example, column-wise semantic type detection and cleaning, clean the column names, standardize missing values, downcast the column data types to be the smallest possible (i.e, use less memory).
* `clean_currency()` - clean currency data ([tentative design](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_currency.ipynb))

### Efficiency

We would like to investigate how to make dataprep.clean fast while balancing the tradeoff of adding additional code complexity. Some ideas [here](https://github.com/sfu-db/dataprep/issues/441).

### Type Detection

Given our ability to validate many semantic types, we would like to determine whether we should support some type detection APIs. For example, perhaps a function such as `detect_type(df, column)`.

### Marketing

* Write a Medium article
* Record a YouTube video
* Reply to StackOverflow posts
* Create a post on Reddit

---

@atol, @qidanrui, @peterirani, and @ryanwdale, please let us know if you have any comments or other ideas, and whether there are any components you are particularly interested in working on. Please feel free to comment on this issue or talk to your mentors.

**Comment by peterirani** [comment]
Hi @brandonlockhart, thanks for sharing the plan - it looks great! I would be interested in **new cleaning functions, type detection**  and **efficiency improvement areas** for Spring 2021. Please let me know if you have any preferences or an order in which you would like these tasks to be done?

**Comment by ryanwdale** [comment]
The plan looks great! I'd be most interested in working on `clean_duplication()`, `clean_df()`, type detection and improving efficiency. It all seems interesting though so I can work on whatever needs to be done.

**Comment by atol** [comment]
Thanks for putting together the plan, @brandonlockhart! Since I'm working on `clean_names()` right now, I think `clean_ml()` and `clean_text()` would follow nicely as my next tasks. I'd also be happy to contribute to a Medium article.
