### ISSUE TITLE
Feature Proposal : clean_currency functionality in clean module.

### ISSUE THREAD

**Issue by peterirani** [sfu-db/dataprep#459]
**Is your feature request related to a problem? Please describe.**
Implement a function `clean_currency` in the clean module which cleans the format of the currency. It would also help in converting one currency to other (for eg: convert CAD to USD).

**Describe the solution you'd like**
The function signature would be as follows:
 
```
def clean_currency(
    dataframe : Union[pd.DataFrame, dd.DataFrame],
    column : str,
    n_round: int = 2,
    consistent_currency: bool = False,
    target_currency: str = "USD",
    target_representation: str = "abbreviation",
    customized_rule = str = None
    split = False 
) -> Union[pd.DataFrame, dd.DataFrame]:
```

* **dataframe:**  pandas.DataFrame input dataframe

* **column: str**
   *  The column to be transformed
   *  Each value within the column is detected, if it's detected as currency type, then it's cleaned. Otherwise, the function does nothing to the value.
   * Currency_Type_Detection and parsing
     * Can be parsed as both currency and value
     * May not contain currency (pure value)
     * Supported currency format prefix: symbol ('$') and abbreviation ('USD')
     * Refers to MessyTable.CurrencyType: https://github.com/okfn/messytables/blob/master/messytables/types.py
     

* **n_round: int**
  Number of digits to be preserved to make format consistent
      Example:
        USD 25.00
        USD 25.0
        USD 25
   
* **consistent_currency: Boolean**
  Indicate whether to transform inputs into consistent currency
  If it's set to false, just keep the initial input currency, otherwise, transform to target_currency
  Example: USD 25.00 <-> RMB 173.64
  Can be done using exchange API: https://exchangeratesapi.io/
  
* **target_currency: str**
  Indicate the target currency
      Can be ignored in terms of currency transformation if consistent currency is set to False. However, it can still serve as default currency
      Can support main currency
      Example:
        USD 25.00
        RMB 173.64
        25.00

* **use_symbol: Boolean**
  whether to use "symbol" ("$")

* **use_abbr: Boolean**
  whether to use "abbreviation" ("USD")
  use_symbol and use_abbr can't be True at the same time

* **customized_rule: Function**
  Defines customized format transfomation function
  Takes input string and output the corresponding output string

* **split: Boolean**
  Define whether to split time attribute into different columns
  Parse and split string to individual components
  components: prefix(abbr/symbol) and amount

**Key points**
  Parse input string into different components
  Fix missing components based on default setting
  Target currency: when the prefix can't be parsed, it just serves as the default currency

**Additional context**
To use data connector to get live conversion rates between different currency pairs.

**Comment by brandonlockhart** [comment]
Nice feature proposal @peterirani! I just have two comments about the parameters:

1. If I understand correctly, the user needs to set the two parameters `consistent_currency=True` and `target_currency ="USD"` to convert the data into USD. I wonder if we could instead make the `target_currency` parameter optional with default `None`, that is `target_currency: Optional[str] = None`, and remove the `consistent_currency` parameter. Then the user only needs to set `target_currency = "USD"` to convert to USD. If `target_currency` is left unspecified, we do not convert between currencies.
2. I don't think we need to implement the `customized_rule` parameter as we decided not to include it in the other functions at this point. But if there is some special use case or functionality for `clean_currency` that requires it, then we can keep it.

**Comment by peterirani** [comment]
Thanks for the input @brandonlockhart! 

- Yes, I think we get  omit `customised_rule`  because this will complicate the function. In future if needed we can always implement it. 

- For `target_currency` we can change the default value to be `None`. Also I feel the name `consistent_currency` does not sound very intuitive. Instead having something like `convert_currency : bool = true` conveys the purpose of the parameter more appropriately. 

-  I think we also need to add a field for `input_currency`, this will be helpful in the conversion process. For example `input_currency :  Optional[str]=None`

Please have a look at the following signature and let me know your thoughts on it! 

```python3
def clean_currency(
    dataframe : Union[pd.DataFrame, dd.DataFrame],
    column : str,
    n_round: int = 2,
    convert_currency: bool = True,
    input_currency = Optional[str] = None,
    target_currency: Optional[str] = None,
    target_representation: str = "abbreviation",
    split = False 
) ->  Union[pd.DataFrame, dd.DataFrame]:
```

**Comment by brandonlockhart** [comment]
I'm still confused about why we need the `convert_currency` parameter. From what I understand
* If `target_currency  is None`, then necessarily `convert_currency = False`. (there's nothing to convert to)
* If `target_currency is not None`, then necessarily `convert_currency = True`. (you will convert to the target currency as necessary)

So I think we can remove `convert_currency`. Sorry if I'm missing something here. The rest looks good to me!

**Comment by peterirani** [comment]
Hi @brandonlockhart, I see your point. Yes, we can omit the `convert_currency` parameter. So if the `target_currency` is set to `None` (default value), it implies that there is no need for conversion.
