### ISSUE TITLE
plot_missing(df, x): several bugs

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#46]
I found a few bugs when running **plot_missing(df, 'HDI_for_year')**.

**Bug 1.** Would be better to let the user know not all countries are displayed. Please work with @brandonlockhart to check how to add ngroups here and also take a look at #42 . 

<img width="614" alt="Screen Shot 2019-12-20 at 9 46 51 PM" src="https://user-images.githubusercontent.com/1028970/71303771-4f2fd480-2372-11ea-83ed-2dc3c8b1e896.png">

**Bug 2.**  Orange bars are not displayed on the _sex_ and _age_ tabs. 

<img width="582" alt="Screen Shot 2019-12-20 at 9 48 07 PM" src="https://user-images.githubusercontent.com/1028970/71303793-8900db00-2372-11ea-8a86-9591573d5a45.png">

**Bug 3**. No bars are displayed on the _country_year_ and _gdp_for_year_ tabs.

<img width="602" alt="Screen Shot 2019-12-20 at 9 51 04 PM" src="https://user-images.githubusercontent.com/1028970/71303816-d8470b80-2372-11ea-8e75-50d0b1913d89.png">

**Comment by dovahcrow** [comment]
The problem of 2 and 3 is that the minimal value of the y axis is equal to the only value the histogram has. e.g. in bug 3, the only value is 12 and all the bar height is 12.

I changed the y-axis range to (0.95 * min(height),  1.05 * max(height)).

**Comment by jnwang** [comment]
Thanks. Is there any reason for not setting min_y = 0?

**Comment by dovahcrow** [comment]
@jnwang No. I changed the minimum to 0.

**Comment by jnwang** [comment]
I thought you set the minimum to “0.95 * min(height)”. Setting it to 0 makes more sense to me.
