### ISSUE TITLE
DataPrep.Connector: Failed to fetch all publications of one specific author

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#465]
**Describe the bug**
I was able to get all publications of a specific author via DataPrep.Connector before, but now it stopped working. 

**To Reproduce**

```python
from dataprep.connector import Connector

conn_dblp = Connector("dblp", _concurrency = 5)
df = await conn_dblp.query("publication", first_name = "Andrew", last_name = "Ng", _count = 2000)
```

**Expected behavior**
It should run successfully and return all of Andrew Ng's publications as a DataFrame. 

**Screenshots**

<img width="817" alt="Screen Shot 2020-12-30 at 3 58 55 PM" src="https://user-images.githubusercontent.com/1028970/103387340-f122ea80-4ab7-11eb-95c8-b8f3a1374a81.png">

Desktop (please complete the following information):

OS: MacOS Catalina
Browser: Chrome
Platform: Jupyter Notebook
Platform Version 6.0.1
Python Version 3.7.4
Dataprep Version 0.2.4

**Comment by dovahcrow** [comment]
fixed in 9a8c6bfc7c1ef73f5f11350a0a0d94d7f26202d4
