### ISSUE TITLE
0.2.15: Malformed boxplot with 2-column plot() when type is "object"

### ISSUE THREAD

**Issue by dhuntley1023** [sfu-db/dataprep#469]
I have a pandas dataframe with a categorical column with 2 values, and also a continuous numeric column.  I'm using dp.plot() to create an analysis of these two columns.  When I cast the categorical column to type "str", the plot displays correctly.  When I cast it to "object", it is not.  Browser is FireFox 84.0.1 on Windows

**Data used in repro below (100 rows):** 
[plot_test_data.zip](https://github.com/sfu-db/dataprep/files/5774340/plot_test_data.zip)

**GOOD GRAPH:  Column cast to 'str'**
![image](https://user-images.githubusercontent.com/5771249/103739674-c7336180-4faa-11eb-9d3b-ab93ddd05900.png)

**BAD GRAPH: Column cast to 'object'**
![image](https://user-images.githubusercontent.com/5771249/103739771-ed590180-4faa-11eb-8117-810e8e142df8.png)

**Comment by dovahcrow** [comment]
nice catch! @jinglinpeng any ideas?

**Comment by brandonlockhart** [comment]
Thanks @dhuntley1023 for creating this issue and providing the data!

With type 'object', the intermediate df for the box plot stores the group names (0.0 and 1.0) as floats (whereas with 'str', they are objects). So I think Bokeh is trying to align the elements with the group names and Bokeh plot markers (0 is the y axis, 1 is the point equidistant from the x ticks). I converted the group names in the intermediate df to string in PR #470 which resolves the problem. 

![Screen Shot 2021-01-06 at 11 16 19 PM](https://user-images.githubusercontent.com/25874021/103863946-9a4c8080-5076-11eb-97a2-fc21dd9c3006.png)
