### ISSUE TITLE
plot_missing(df, x, y): several bugs

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#47]
I found a few bugs after running **plot_missing(df, x, y)**.

**Bug 1.** DropMissing should be orange and Origin should be blue. Also, the PDF curve looks strange to me. Please double-check whether it is correct.

<img width="609" alt="Screen Shot 2019-12-20 at 11 10 41 PM" src="https://user-images.githubusercontent.com/1028970/71304701-e3a03400-237e-11ea-83c4-4e7207feaa26.png">

**Bug 2.** The two CDF curves overlap, which looks strange to me.
<img width="581" alt="Screen Shot 2019-12-20 at 11 17 50 PM" src="https://user-images.githubusercontent.com/1028970/71304709-07637a00-237f-11ea-8506-2401c5efbd52.png">

**Bug 3.** Please make the box plot consistent with the one generated by plot(df, numerical_x). Also, the color scheme of the box plot looks strange to me. 

<img width="486" alt="Screen Shot 2019-12-20 at 11 18 55 PM" src="https://user-images.githubusercontent.com/1028970/71304726-1ea26780-237f-11ea-8ce1-b4e033cf3c0a.png">

**Comment by dovahcrow** [comment]
@jnwang The missing values are sort of evenly distributed so you observe nearly no change after drop missing for CDF and PDF. You can check out the histogram.
![image](https://user-images.githubusercontent.com/998606/71599768-75d7d300-2b09-11ea-8b86-1e2993b75702.png)

**Comment by jnwang** [comment]
It makes sense. Can you please check Bug 3?

**Comment by dovahcrow** [comment]
@jnwang It's fixed in #56
