### ISSUE TITLE
Finnhub config validation error for commercial_news, ipo_calender and earnings_calender

### ISSUE THREAD

**Issue by salcaino** [sfu-db/dataprep#473]
The following error occurs with the latest version of Finnhub config files.

pydantic.error_wrappers.ValidationError: 3 validation errors for ConfigDef
request -> params -> from -> __root__
  template requires {'from_'} exist in fromKey, got set() (type=value_error)
request -> params -> from
  value could not be parsed to a boolean (type=type_error.bool)
request -> params -> from
  str type expected (type=type_error.str)

this is the case for these three files:
commercial_news.json
ipo_calender.json
earnings_calender.json

**Comment by peiwangdb** [comment]
@salcaino thanks for the issue! Investigating on it!

**Comment by dovahcrow** [comment]
Hi @salcaino, the issue is fixed. Try this piece of code:
```python
dc = connect("finnhub", _auth={"access_token":"***"}, update=True)
df = await dc.query("earnings", symbol="AAPL")
df.head()
```

**Comment by salcaino** [comment]
I can confirm the issue has been fixed. thank you so much for the quick response and fix!
