### ISSUE TITLE
Query is not paging automatically

### ISSUE THREAD

**Issue by KrinceLiu** [sfu-db/dataprep#477]
**Describe the bug**
I'm collecting data from 'guardian', and the returned dataframe rows are repeated with only 10 unique rows even I increase '_count'.
 It seems the program is not paging, it is staying on the first page and keep pulling data from first page.

**To Reproduce**
you can use my API key to reproduce the result

```python
API_key = "4d9570dd-2795-4347-b0e4-aab71dedcb51"

from dataprep.connector import connect, info, Connector
conn_guardian = connect('guardian', _auth={'access_token': API_key}, concurrency=3)

df = await conn_guardian.query('article', _q='university', _count=20)
print(df.shape)
print(df.drop_duplicates().shape)
```

**Returned Result**

<img width="813" alt="Screen Shot 2021-01-17 at 1 35 02 PM" src="https://user-images.githubusercontent.com/27181658/104856866-ab448f80-58c9-11eb-9720-0551e8c157e3.png">

**Comment by yxie66** [comment]
Fixed in https://github.com/sfu-db/DataConnectorConfigs/pull/60.
