### ISSUE TITLE
plot(df) and plot_correlation(df) fail when data has 'list' columns

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#48]
When running plot(df) and plot_correlation(df) on the following dataframe, since the author column is a list, both plot and plot_correlation failed. 

For plot(), the reported error is `TypeError: unhashable type: 'list'`

For plot_correlation(df), the reported error `AssertionError: No numerical columns found`

<img width="520" alt="Screen Shot 2019-12-21 at 1 36 30 PM" src="https://user-images.githubusercontent.com/1028970/71314072-fe15f400-23f6-11ea-95f5-c0a0bdd33599.png">

**Comment by brandonlockhart** [comment]
This has been fixed for plot()
![image](https://user-images.githubusercontent.com/25874021/71372178-82d44f80-2568-11ea-89fb-ac7a8a444cec.png)

**Comment by Waterpine** [comment]
@jnwang I think the reason is that plot_correlation() function only supports for numerical data. It is impossible for us to calculate a correlation value between list or categorical data. Thus, I believe that we could solve this problem in the next version. Thanks!

**Comment by jnwang** [comment]
Can you please check how df.corr() handles this? It would be better if we can make plot_correlation() consistent with df.corr()?

**Comment by Waterpine** [comment]
@jnwang @dovahcrow df.corr() also does not handles this. There is nothing output when we use the df.corr() function.
<img width="1130" alt="屏幕快照 2020-01-03 下午4 32 52" src="https://user-images.githubusercontent.com/29000790/71713951-d424ee80-2e46-11ea-8de4-b50632b8326f.png">

**Comment by jnwang** [comment]
It looks like that df.corr() automatically ignores non-numerical columns. Can we do the same rather than raise an error?

https://www.geeksforgeeks.org/python-pandas-dataframe-corr/amp/

**Comment by Waterpine** [comment]
@jnwang @dovahcrow @jinglinpeng I have fixed this bug. The plot_correlation() function only supports for numerical data. Plot_correlation() will ignore non-numerical data and output nothing when the input data is not numerical. If you have any questions, please let me know as soon as possible. Thanks! #57 
![Screenshot from 2020-01-04 03-32-59](https://user-images.githubusercontent.com/29000790/71764915-019f8580-2ea3-11ea-8cbf-70b7b41e9997.png)

**Comment by dovahcrow** [comment]
@jnwang why empty output is good? I feel like a hard error is more explicit than an implicit empty return, and explicit is better than implicit.

**Comment by jnwang** [comment]
We should output an empty plot if all cols are non-numerical. I think we did it for plot_correlation(k).

**Comment by Waterpine** [comment]
@jnwang @dovahcrow I agree with young. However, an empty plot is also a good option.

**Comment by dovahcrow** [comment]
Let do empty and can make it error later if users are complaining.

**Comment by Waterpine** [comment]
Okay, I have fixed this bug. Thanks! #57
