### ISSUE TITLE
Feature Proposal: clean_address functionality in clean module

### ISSUE THREAD

**Issue by ryanwdale** [sfu-db/dataprep#481]
## Summary

Implement a function `clean_address()` that cleans messy US addresses and converts them between different formats.

## Design-level Explanation Actions

- [x] Investigate prior solutions for cleaning addresses.
- [x] Decide which features to support.

## Design-level Explanation

Proposed function signature for `clean_address()`:
```python
def clean_address(
    df: Union[pd.DataFrame, dd.DataFrame],
    column: str,
    input_format: str = "auto",
    output_format: str = "(building) house_number street_prefix_abbr "
                         "street street_suffix_abbr apartment, city, state_abbr zipcode",
    must_contain: Tuple[str] = ("house_number", "street"),
    split: bool = False
) -> pd.DataFrame:
```

### `input_format` parameter

Formats can be specified via the following keywords:
* house_number
* street_prefix_abbr ("N", "S", "E", or "W")
* street_prefix_full ("North", "South", "East", or "West")
* street
* street_suffix_abbr (eg "St", "Ave")
* street_suffix_full (eg "Street", "Avenue")
* apartment
* building
* city
* state_abbr (eg "NY")
* state_full (eg "New York")
* zipcode

All of the keywords in the input format string must be present and in the specified order for the string to be successfully cleaned. The default is "auto" which infers the input format.

For example:
If `input_format = "house_number street city"`

"1600 Pennsylvania, Washington" => "success"
"1600 Pennsylvania Avenue" => "fail"

If any attribute of the address is missing or in the wrong order the input won't be successfully cleaned.

### `output_format` parameter

Formats can be specified using the same keywords as for the `input_format` parameter. The default is "(building) house_number street_prefix_abbr. street street_suffix_abbr. apartment, city, state_abbr zipcode", any missing attributes are omitted.

Extra characters that aren't keywords can be included and will appear in the output.

For example:
`"1600 Pennsylvania Avenue, Washington, DC", output_format = "(house_number) street, state_abbr"` => "(1600) Pennsylvania, DC"
`"1600 Pennsylvania Avenue, Washington, DC", output_format = "address: house_number, street"` => "address: 1600, Pennsylvania"

The user can also specify how to split the address into columns using "\t".

*Example.* df = 

| address |
| --- |
| 1600 Pennsylvania Avenue, Washington, DC 20500 |

`clean_address(df, "address", output_format = "house_number street street_suffix_abbr. \t city \t state_abbr")` returns,
| address | house_number_street_street_suffix | city | state|
| --- | --- | --- | --- |
| 1600 Pennsylvania Avenue, Washington, DC 20500, USA | 1600 Pensylvania Ave. | Washington | DC |

`output_format` can also be set to "dict". This will output a dictionary containing the name of address attributes as keys and the corresponding part of the address as values.

`clean_address(df, "address", output_format = "dict")` returns,
```json
{
  "house_number": "1600",
  "street": "Pensylvania",
  "street_suffix": "Avenue",
  "city": "Washington",
  "state": "DC",
  "zipcode": "20500"
}
```

### `must_contain` parameter

A tuple of address attributes that must be found in the address for it to be successfully cleaned. By default `must_contain = ("house_number", "street")`. Order doesn't matter and the address may contain extra attributes that aren't in `must_contain`. This parameter allows for validating addresses in a more permissive way by default and allowing the user to make it more strict if they wish. 

### `split` parameter

If True, the output will be split into each identified attribute of the address.

*Example.* df = 
| address |
| --- |
| 1600 Pennsylvania Avenue, Washington, DC 20500 |

`clean_address(df, "address", split=True)` returns
| address | house_number | street | street_suffix | city | state| zipcode |
| --- | --- | --- | --- | --- | --- | --- |
| 1600 Pennsylvania Avenue, Washington, DC 20500 | 1600 |Pennsylvania | Avenue | Washington | DC | 20500 |

Attributes not present in the `output_format` will be omitted. 

`clean_address(df, "address", output_format="street, city", split=True)` returns
| address | street |  city | 
| --- | --- | --- | 
| 1600 Pennsylvania Avenue, Washington, DC 20500 | Pennsylvania | Washington | 

I'm planning on ignoring any extra characters found in `output_format` when `split = True` because setting split to True and leaving `output_format` as the default creates an awkward looking case with many attributes ending in a comma.

Proposed function signature for `validate_address()`:
```python
def validate_address(
    x: Union[str, pd.Series], input_format: str = "auto", must_contain: Tuple[str] = ("house_number", "street")
) -> Union[bool, pd.Series]:
```
All parameters work the same as in `clean_address()`.

## Implementation-level Explanation

The implementation when `input_format = "auto"` is based on [pyaddress](https://github.com/SwoopSearch/pyaddress).
Here's a simplified explanation of the algorithm, first the input is split on whitespace into tokens. The algorithm starts at the back since easily identified attributes such as zip code and state are usually found near the back. For each token attributes are checked until a match is found (in an order such that attributes more likely to be found near the back are checked first). 
Individual attributes are checked based on a number of rules, for example street suffix must come before the street, street name must come before the house number (in reverse order).

For other input formats, I'm currently using a greedy approach. The algorithm starts at the back of the address and while there is a match with the current part of the input format it continues (basically grabbing as much of the address matching the current attribute as it can before moving on). It's difficult because I don't have a lookup table for street names, so street names could be anything. This leads to problems when there's an `input_format` with street name towards the end. I'm planning on experimenting with more of a brute force approach that explores all possible paths. 

## Rationale and Alternatives

This design is simple while still providing enough functionality for most common use cases. An alternative would be to use the [usaddress](https://github.com/datamade/usaddress) library to parse the input, some extra work would need to be done to clean/standardize the address. This would be similar to [usaddress-scourgify](https://github.com/GreenBuildingRegistry/usaddress-scourgify) (this library calls the usadress library). This might be a bit more complex but would provide better results than the current implementation, especially on edge cases. 

## Prior Art

-  [pyaddress](https://github.com/SwoopSearch/pyaddress) Cleans addresses based on a set of specific rules.
- [usaddress](https://github.com/datamade/usaddress) Uses probablistic model to guess components.
- [usaddress-scourgify](https://github.com/GreenBuildingRegistry/usaddress-scourgify) Uses the usaddress library, standardizes the result in USPS format.

## Future Possibilities

Adding support for addresses from other countries. This could potentially be done using [libpostal](https://github.com/openvenues/libpostal) an NLP library for parsing addresses that supports many countries and languages. A `location` parameter could be added to specify which implementation to use, when set to "US" the US based implementation outlined above is used, when set to "international" an implementation based on libpostal is used. Specific implementations could also be added for individual countries as needed. 

## Implementation-level Actions

- [x] Implement the functions
- [ ] Test on real world data sets

## Additional Tasks

- [x] This task is put into a correct pipeline (Development Backlog or In Progress).
- [x] The label of this task is setting correctly.
- [x] The issue is assigned to the correct person.
- [x] The issue is linked to related Epic.

- [ ] The documentation is changed accordingly.
- [ ] Tests are added accordingly.

**Comment by brandonlockhart** [comment]
Really nice description Ryan! I like your choices and agree with your justifications. I particularly like the `must_contain` parameter. Nice to see that you will test it on real-world data too.

Do you think adding support for Canadian addresses will be difficult in the future? I wonder if they could be parsed similarly to American.

**Comment by ryanwdale** [comment]
Thanks Brandon! I think Canadian addresses could be parsed in a similar way. The current approach uses dictionaries of US cities and states, so I would just need to add Canadian cities and provinces to those. I'd also add a "province" keyword for the `input_format` and `output_format` parameters.

**Comment by brandonlockhart** [comment]
Cool! If it's easy and fast to do, I think we should add Canadian addresses now. However, I'm also okay with leaving this as a small feature enhancement we do in the future. @ryanwdale you can decide, unless others feel strongly one way or the other.

A small thing: I think we can also consider a keyword for postal code rather than zip code for Canada.

**Comment by ryanwdale** [comment]
Sounds good, I'll plan to do it now but if it ends up being harder than I expect I might leave it for a later PR.
