### ISSUE TITLE
data_connector: dblp schema

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#49]
Please check the dblp schema below.

<img width="1115" alt="Screen Shot 2019-12-21 at 1 53 52 PM" src="https://user-images.githubusercontent.com/1028970/71314298-79c57000-23fa-11ea-92e5-f21889ddc811.png">

1. I suggest using author**s** as a column name since it has more than one author.

2. I suggest using page**s** as a column name since it has more than one page.

3. Why is the data type of the `venue` column a list? Should it be string?

**Comment by peiwangdb** [comment]
1. columns names are updated.
2. venue can be a list.

<img width="477" alt="Screen Shot 2019-12-21 at 3 24 36 PM" src="https://user-images.githubusercontent.com/15167104/71314883-09245080-2406-11ea-9875-fbcfaf401d80.png">

**Comment by jnwang** [comment]
Thank you!
