### ISSUE TITLE
dataset insights does not render correctly 

### ISSUE THREAD

**Issue by gverbock** [sfu-db/dataprep#514]
**Describe the bug**
When the input dataframe has column names composed of one letter, this letter is 'removed' from the text.

**To Reproduce**

```python
import pandas as pd
from dataprep.eda import plot, plot_correlation, plot_missing

value_col = [nb for nb in range(100)]
X = pd.DataFrame({"a": value_col, "n": value_col, "v": value_col})
```
Then click on Show Stats and Insights and look at the text in Dataset Insights

**Expected behavior**
[a] nd v hve similr distributions => [a] and v have similar distributions
Same type of issue for the other columns (n and v)

**Screenshots**
![image](https://user-images.githubusercontent.com/32060943/108869611-a5904700-75f7-11eb-9aa2-bb9a046eaa13.png)

**Additional context**

**Comment by brandonlockhart** [comment]
Thanks for creating this issue @gverbock! @eutialia do you know why this is happening? I think [this line](https://github.com/sfu-db/dataprep/blob/5878dc0fc9a24eff81ec09dd77bd56a3523d7e7b/dataprep/eda/templates/grid_base.html#L117) might be the problem.
