### ISSUE TITLE
feat(clean): handle phone numbers containing letters

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#527]
**Is your feature request related to a problem? Please describe.**
Some phone numbers encode numbers as letters. E.g., in this [dataset](https://data.cityofnewyork.us/City-Government/Trade-Waste-Hauler-Licensees/867j-5pgi) there is the phone number '800-299-JUNK', which is currently identified as being invalid in `clean_phone()`.

**Describe the solution you'd like**
I'm wondering if we can update the regular expressions to accommodate letters in phone numbers, and to convert letters to numbers in `clean_phone()` appropriately.

**Comment by atol** [comment]
Hi Brandon, I think we could definitely update `clean_phone()` to accommodate letters in phone numbers and to convert them to the corresponding numbers. My initial thoughts are to allow letters in the office code and station code, e.g. "800-299-JUNK" or "1-800-GOT-JUNK". I don't think I've seen letters in the area code and this would help distinguish the phone numbers from regular strings. Also, I think we should only match uppercase letters for similar reasons.

**Comment by brandonlockhart** [comment]
Thanks for your comment @atol! I agree with all of your initial thoughts.
