### ISSUE TITLE
Dataprep connector for YouTube: 'publishTime' attribute is None

### ISSUE THREAD

**Issue by AT100** [sfu-db/dataprep#532]
For the YouTube API connector, the 'publishTime' attribute always comes as None. 

![image](https://user-images.githubusercontent.com/12692076/111052486-ecf83f00-840f-11eb-9f6d-1edd236b4d63.png)
![image](https://user-images.githubusercontent.com/12692076/111052518-46606e00-8410-11eb-84d9-666b309483d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Platform: Jupyter Notebook
 - Platform Version : 6.1.4
 - Python Version: 3.8.5
 - Dataprep Version: 0.2.15

**Additional context**
There is another attribute named 'publishedAt' that gives a timestamp, but according to the Youtube API documentation [https://developers.google.com/youtube/v3/docs/videos#status.publishAt](url) these are different attributes and can take different values.

**Comment by peiwangdb** [comment]
@AT100 Thanks for the issue. Will look into it and get back to you soon!

**Comment by peiwangdb** [comment]
Hi @AT100 thanks for the bug report! This issue is fixed in the configuration file repo and will be included in the next release!
