### ISSUE TITLE
Dataprep.connector YouTube: 'playlistId' attribute not present for type='playlist' 

### ISSUE THREAD

**Issue by AT100** [sfu-db/dataprep#533]
**Describe the bug**
For the YouTube API connector, the query parameter 'type' can have values 'video', 'channel' or 'playlist'. When type is 'playlist', the actual YouTube API gives 'playlistId' instead of the 'videoId'(screenshots below). However, in the dataprep connector response,  the 'playlistId' is missing and the videoId attribute comes as None.

Response from YouTube API for type='playlist':
![image](https://user-images.githubusercontent.com/12692076/111052842-968cff80-8413-11eb-9679-723712f8eec5.png)

Response from YouTube API when type='video':
![image](https://user-images.githubusercontent.com/12692076/111052924-7447b180-8414-11eb-9ca2-6345374ce1e7.png)

Response from dataprep.connector for type='playlist:
![image](https://user-images.githubusercontent.com/12692076/111052874-f2578880-8413-11eb-9d63-50c1b34ca9ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Platform: Jupyter Notebook
 - Platform Version: 6.1.4
 - Python Version: 3.8.5
 - Dataprep Version: 0.2.15

**Comment by peiwangdb** [comment]
Hi @AT100, thanks a lot for the issue! It seems that the playlistId is dependent on the type parameter. I am sorry that We currently can not support this scenario. Alternatively, you can download the config file from here https://github.com/sfu-db/DataConnectorConfigs/tree/develop/api-connectors and edit the corresponding field manually. And then load the config file locally.

**Comment by peiwangdb** [comment]
@Lakshay-sethi this is a case that we can not support now and will consider supporting in the future.
