### ISSUE TITLE
data_connector (Spotify): missing cols in the Artist and Album tables 

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#54]
Is there any reason for **not** including external_urls, images for the `Artist` table and for **not** including popularity, album_type, copyrights, external_urls for the `Album` table?

Also, in the Album table, can an album have more than one artist?

**Comment by peiwangdb** [comment]
Refined Artist and Album table.
Added "image url" and "external_urls" for artist.
Added " album_type", "external_urls" for albums.
