### ISSUE TITLE
Feature(Connector): Function to allow dynamic website generation 

### ISSUE THREAD

**Issue by Lakshay-sethi** [sfu-db/dataprep#544]
**Is your feature request related to a problem? Please describe.**
Currently we support the most commonly found type of api request, but as we are growing we need to start including more and more edge types of api requests.

**Describe the solution you'd like**
I would like to build a function that would work as a intermediator between the parameters we get from query function and the url parameter from config files

**Looking for suggestions**
If anyone can make a collection of different types of api requests here, it would be much appreciated.
Also, currently the scope of this issue is too open and would lie to request everyone to help me formulate the requirements in a concise fashion.

**Comment by nick-zrymiak** [comment]
Some endpoints that only have one parameter available don't include the parameter name in the URL.

Example
OurAirport API geolocate endpoint parameter:
- ipAddress

Let's say we want to set ipAddress to "8.8.8.8"

This is what the URL needs to look like: https://ourairport-data-search.p.rapidapi.com/geolocate/8.8.8.8

The parameter name "ipAddress" is not specified, only its value.

**Comment by nick-zrymiak** [comment]
Many APIs such as those made available by the Canadian Government have this response structure:

![image](https://user-images.githubusercontent.com/35017006/112395422-95818b00-8cbb-11eb-94d2-e965924ae882.png)

The first section contains column names and the second section contains one section for each row and values.

Would be great if we could support this structure!

**Comment by peiwangdb** [comment]
@Lakshay-sethi great point! And to clarify, can you 1). list the websites or APIs you can support now; 2). list the cases that your current code can not cover (but you think can be relevant) 3). the cases that you find ambiguous and explain what needs to be clarified. Hopefully by doing this everyone can be on the same page and find the agreement on the scope.

**Comment by Lakshay-sethi** [comment]
> Some endpoints that only have one parameter available don't include the parameter name in the URL.
> 
> Example
> OurAirport API geolocate endpoint parameter:
> 
> * ipAddress
> 
> Let's say we want to set ipAddress to "8.8.8.8"
> 
> This is what the URL needs to look like: https://ourairport-data-search.p.rapidapi.com/geolocate/8.8.8.8
> 
> The parameter name "ipAddress" is not specified, only its value.

can be supported most probably, look into my PR

**Comment by Lakshay-sethi** [comment]
> Many APIs such as those made available by the Canadian Government have this response structure:
> 
> ![image](https://user-images.githubusercontent.com/35017006/112395422-95818b00-8cbb-11eb-94d2-e965924ae882.png)
> 
> The first section contains column names and the second section contains one section for each row and values.
> 
> Would be great if we could support this structure!

Sorry, I am not working on response. Please bring it up in the meeting.

**Comment by Lakshay-sethi** [comment]
## Current cases supported
- Any url with can be updated by placing variable in {}
http://api.mapbox.com/geocoding/{d}/mapbox.places/{s}.json -> http://api.mapbox.com/geocoding/v5/mapbox.places/chester.json
## Cases can be supported
- A case in which e can specify signs to divide different parameters (Currently code can take input, working on how to use that input in a general way)
http://api.mapbox.com/geocoding/{d}/mapbox.places/{s}.json -> http://api.mapbox.com/geocoding/v5/mapbox.places/-77.1,-67.4;112.3,33.45.json

**Comment by dovahcrow** [comment]
@Lakshay-sethi can you write down how do we handle these two tasks?
Given URL: `https://foo.bar.com/{a}/{b}`, we need to:
1. generate a set `{"a","b"}` from the URL to that we can get the required parameter from the user input.
2. instantiate the URL into `https://foo.bar.com/alpha/2` given a dictionary `{"a": "alpha", "b": 2}`.

These two parts is not very clear to me for now. Thanks!

**Comment by Lakshay-sethi** [comment]
part 3 can be handled by passing a false in the parse variable
