### ISSUE TITLE
clean_date() mixes up formats of date in one column

### ISSUE THREAD

**Issue by NoirTree** [sfu-db/dataprep#599]
**Describe the bug**

**To Reproduce**
From this [dataset](https://www.kaggle.com/lorilaz/apple-news-headline-sentiment-and-stock-info), or just see the following demo:

```python
df = pd.DataFrame(
    {'date': ['12-01-06', '12-04-06', '12-05-06', 
              '20-12-06', '21-12-06', '29-12-06']})
clean_date(df, 'date')
```
![image](https://user-images.githubusercontent.com/66409637/115706248-00e47880-a3a0-11eb-9847-040e6a76924a.png)

**Expected behavior**
The correct format should be 'DD-MM-YY', but `clean_date` interpret the first three lines as 'MM-DD-YY' and the last three lines as 'DD-MM-YY'. 

It is understandable that correct format is hard to infer from the first three lines, but we can recognize it from other data in the same column. As data format is mostly consistent in one column, it might be a good idea to let `clean_date` do some inference and do a better job.
Or even if we cannot make correct judgement, it might be more reasonable for `clean_date` to behave consistently in one column.

**Comment by qidanrui** [comment]
Hi, Jingxuan. Thank you for finding this issue. Great advise! @NoirTree 

For your consideration. For the datetime format like `12-01-06`, I set the default format as `MM-DD-YY`. However, when encountering some datetime like `20-12-06`, it is obvious that the number which is larger than 12 should be the date value. If I set the default format as `DD-MM-YY`, some dataset may include `12-20-06`, which is also a hard situation to be handled. 

Thus, I have a solution of adding a trigger. For example, if the data includes `12-20-06` and if we have already figured out that `20` is in the second place, then we can treat the second place as day number for the whole column. If the data includes `20-12-06` and if we have already figured out that `20` is in the first place, then we can treat the first place as day number for the whole column. If you think this solution can solve your consideration, please let me know. If you still think it is not reasonable, we can continue discussing on this page~

The above solution is based on your advise "As data format is mostly consistent in one column, it might be a good idea to let clean_date do some inference and do a better job.". Great job! Thanks~

**Comment by NoirTree** [comment]
@qidanrui Thank you for your reply! That is exactly what I hope `clean_date()` can do :D

**Comment by qidanrui** [comment]
> @qidanrui Thank you for your reply! That is exactly what I hope `clean_date()` can do :D

Got! I will try to fix this bug. Thanks for your advise. If there are other bugs in `clean_date()`, please feel free to propose them~Thanks!

**Comment by qidanrui** [comment]
Hi, Jingxuan. @NoirTree 
Please refer to the pull request #627 to see if your requirements are satisfied.
If yes, I'll merge the code and update documentation.
Thanks~

**Comment by NoirTree** [comment]
Hi, @qidanrui .
Thanks! I have tried it out and it works as expected. Great job~
