### ISSUE TITLE
clean:  alternative choices for the default value of `clean_date`

### ISSUE THREAD

**Issue by NoirTree** [sfu-db/dataprep#609]
Currently the default value for missing data in `clean_date` is January 1st, 2000, but this may result in confusion if the dataset actually contains date as 2000-01-01 (which is not a missing value). And suppose that our user wants to count how many times 2000-01-01 appears, then he will get a wrong answer.

**Describe alternatives you've considered**
It may be a better choice to set some invalid date as the default value. For example, [PATSTAT](http://documents.epo.org/projects/babylon/eponot.nsf/0/225F09FAA60945C2C125855F002797C2/$File/PATSTAT_DataCatalog_Global_v5-17.pdf) set "9999-12-31" as default missing value to avoid collision. Maybe we can borrow this idea?

**Comment by qidanrui** [comment]
Thank you for figuring out this, Jingxuan! @NoirTree
I agree with your opinion and I think your proposed solution is reasonable.  It will be a great enhancement. Let me fix it. Thanks~

**Comment by qidanrui** [comment]
Hi, Jingxuan. @NoirTree 

I double checked this bug. My implementation is based on [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html). When you input a string like `10pm`, [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html) will return `datetime.datetime(2021, 5, 8, 22, 0)` to you. It means that [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html) imputes missing values with current year, month and day. 

In my implementation, as you say, the default value for missing values in clean_date is January 1st, 2000.  However, if we set the missing values to "9999-12-31", the year value 9999 becomes invalid, which does not follow our goal of cleaning date format.

I think there are two solutions:  (1) follow the design of [dateutil](https://dateutil.readthedocs.io/en/stable/parser.html) and change the default `fix_missing` parameter to `current`. (2) Let users to specify the imputation value they want.

What is your opinion?

**Comment by NoirTree** [comment]
Hi, @qidanrui . Thanks for your attention to this matter!

> However, if we set the missing values to "9999-12-31", the year value 9999 becomes invalid, which does not follow our goal of cleaning date format.

I'm still a bit confused with this goal yet. When aiming at cleaning date format, we may only need to keep the date format valid and consistent (e.g. "May 2, 2021" and "2021/06/29" are transformed to "2021-05-02" and "2021-06-29"). I think `clean_date` doesn't need to replace the invalid date with a valid one, since a valid value may not be a correct one, which may lead to confusion. 

Instead, we can give users a warning that there exist some invalid values and let them decide what to do with that (as the second solution you give here).

I'm wondering if I understand the the functionality of `clean_date` correctly?

**Comment by qidanrui** [comment]
Hi, Jingxuan. @NoirTree 

I think if users want to count how many times  2000-01-01 appears, he/she can just set the `fix_empty` parameter to `empty`. For example, if the parameter `fix_empty` parameter is set`empty`, the data `10pm` will be `----:--:-- 22:00:00`, which is enough to avoid collision.

**Comment by NoirTree** [comment]
Hi, @qidanrui .
I agree with you! I did not notice the parameter before. Thanks for informing me!
