### ISSUE TITLE
create_report() is throwing error

### ISSUE THREAD

**Issue by THEMrinaal** [sfu-db/dataprep#625]
I was using the dataprep create_report() but I am getting a weird error
```
ValueError: No non-trivial arrays found
```

**Comment by jinglinpeng** [comment]
Hi @THEMrinaal , Thanks for the bug report! Is it possible to share the data and code, so that we can reproduce the error?

**Comment by THEMrinaal** [comment]
Hi @jinglinpeng , I cannot share data as it's confidential data. In terms of code, I just used the documentation provided

**Comment by jinglinpeng** [comment]
Hi @THEMrinaal , thanks for the response. We have fixed some bugs and just released a new version of `dataprep`. Could you try it (`pip install -U dataprep`) and see whether the error still exists?
