### ISSUE TITLE
plot_correlation: handle missing values

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#63]
It looks plot_correlation(df, x) and plot_correlation(df, x, y) cannot handle missing values. Could you please take a look? @Waterpine 

The code is as follows:
`df = pd.read_csv('https://www.openml.org/data/get_csv/9/dataset_9_autos.arff', na_values = ['?'])`
`plot_correlation(df, 'price')`
`plot_correlation(df, 'price', 'bore')`

The running result is as follows:
![Screen Shot 2020-01-21 at 5 18 19 PM](https://user-images.githubusercontent.com/18078770/72857395-59473a80-3c72-11ea-9fa7-77ca12aed276.png)
![Screen Shot 2020-01-21 at 5 18 42 PM](https://user-images.githubusercontent.com/18078770/72857397-5ba99480-3c72-11ea-8dd0-fdba3cc57f65.png)

**Comment by Waterpine** [comment]
I have fixed this bug. If you have any questions, please let me know as soon as possible! Thanks!
@jinglinpeng #64 
<img width="1086" alt="屏幕快照 2020-01-23 下午3 07 19" src="https://user-images.githubusercontent.com/29000790/72963422-380d5800-3df2-11ea-8d7b-04ab0c675a3e.png">

**Comment by jinglinpeng** [comment]
> I have fixed this bug. If you have any questions, please let me know as soon as possible! Thanks!
> @jinglinpeng #64
> <img alt="屏幕快照 2020-01-23 下午3 07 19" width="1086" src="https://user-images.githubusercontent.com/29000790/72963422-380d5800-3df2-11ea-8d7b-04ab0c675a3e.png">

It looks good. Thanks!
