### ISSUE TITLE
`clean_lat_long` mixes up precision

### ISSUE THREAD

**Issue by NoirTree** [sfu-db/dataprep#630]
**Describe the bug**
`clean_lat_long` mixes up precision in one column.

**To Reproduce**
from this [dataset](https://www.kaggle.com/dustinec/2019-baton-rouge-la-animal-control-calls), or see the demo below:

```python3
df = pd.read_csv("./lat_long/BR_Animal_Control_Calls.csv", sep = ',', encoding = "ISO-8859-1")
df = clean_headers(df)
df = df.loc[:, ['lat', 'long']]
clean_lat_long(df, lat_col = "lat", long_col = "long")
```
![image](https://user-images.githubusercontent.com/66409637/118368460-bfc53a00-b5d4-11eb-999c-b19d4295cd57.png)
Most values have 4 decimal places, while some only have 3 (latitude in row 3 and longitude in row 4), and I did not find a place to fix that. Maybe we could add a parameter `precision` to customize the precision, and set the default value as 7, just as the default setting of Google Map (see below)?

![image](https://user-images.githubusercontent.com/66409637/118368474-c6ec4800-b5d4-11eb-9eec-8bf2834defe0.png)

**Comment by yxie66** [comment]
Hello NoirTree,

Thank you very much for creating this issue for Dataprep.

I think the feature you proposed is pratical, and adding parameter is a good idea. However there's some details which should be considered, for example, what will the function behave when the precision of initial data values are non consistent.

We'll look into that and keep the discussion in this thread. You're also welcome to add more details or create your own PR.

Best Regards,
Yi

**Comment by NoirTree** [comment]
Hi @yxie66, thanks for your reply!

As you mentioned, 
> for example, what will the function behave when the precision of initial data values are non consistent.

You are right. In this case the default precision will certainly fail. But I think users may also expect `clean_lat_long` to make the precision consistent in one column/dataset.

Therefore, we can provide several strategies in parameter `precision`, such as "keep the minimal decimal places in the column" (e.g. 3 in the example above) or "keep the decimal places as major values in the column" (e.g. 4 in the example above). We can also allow users to set the exact precision if they want.

**Comment by NoirTree** [comment]
I look into the code and find it actually rounds every value to 4 decimals. Since the extra 0 is ignored when displaying float, the result looks like it mixes up the precision. The issue is just due to my misunderstanding, and I will close it with this comment.
