### ISSUE TITLE
clean_duplication cannot properly handle dataframes not named 'df'

### ISSUE THREAD

**Issue by mpaulonis** [sfu-db/dataprep#646]
**Describe the bug**
When passing a dataframe to clean_duplication, if it is not named 'df', an incorrect statement is inserted into the notebook to show the cleaned dataframe after completing the duplicate removal.  In addition, the need to add the df_var_name argument to the function call to properly create the replace statements if the dataframe is not named 'df' seems unnecessary and confusing.

**To reproduce:**
```python
import pandas as pd
from dataprep.clean import clean_duplication
test = pd.DataFrame(['similar', 'simlar'], columns=['text'])
clean_duplication(test,'text', df_var_name='test')
# after merging a change and then finishing the function, the following statements are inserted into the notebook
test['text'] = test['text'].replace(['simlar'], 'similar')
# dataframe with cleaned string values
df_clean
# returns NameError: name 'df_clean' is not defined
```

**Expected behavior**
The statement to display the dataframe with cleaned string values should be test_clean and it should exist.  The statement is asking to display df_clean, which is not consistent with the name of the input dataframe.  Also, neither df_clean nor test_clean is created by the function.

Why do you require df_var_name='test' as an argument at all?  If the input dataframe is named 'test', then 99+% of the time, someone is going to want the replace statements to reference test['text'], not df['text'].  If there is a need to keep the argument for the unlikely case where someone wants the replace statements to reference something other than the input dataframe name, it would be much better to default df_var_name to be the name of the input dataframe rather than 'df'.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Platform: Jupyter Notebook
 - Platform Version: 6.1.5
 - Python Version: 3.8.5
 - Dataprep Version: 0.3.0

**Comment by AndyWangSFU** [comment]
This is a very interesting bug!
