### ISSUE TITLE
Category column throws TypeError: Categorical cannot perform the operation all

### ISSUE THREAD

**Issue by phoebebright** [sfu-db/dataprep#647]
The dataset has a datetime index and is all floats and ints apart from one categorical column:

```
 23  rh_diff             84 non-null     float64 
 24  we_count_diff           84 non-null     float64 
 25  ae_count_diff           84 non-null     float64 
 26  month                   85 non-null     category
```

which is generated:

    df['month'] = df.index.strftime('%Y/%m %b').astype('category')

**To Reproduce**
Running in Jupyter notebook inside Pycharm:

        create_report(df)

Gives error trace below.  Remove this column or create it as:

    df['month'] = df.index.strftime('%Y/%m %b').astype('object')

and it works fine.  

```python
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-2915-463fb2fdfb17> in <module>
----> 1 create_report(df)

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/__init__.py in create_report(df, config, display, title, mode, progress)
     66         "resources": INLINE.render(),
     67         "title": title,
---> 68         "components": format_report(df, cfg, mode, progress),
     69     }
     70     template_base = ENV_LOADER.get_template("base.html")

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in format_report(df, cfg, mode, progress)
     71         if mode == "basic":
     72             edaframe = EDAFrame(df)
---> 73             comps = format_basic(edaframe, cfg)
     74         # elif mode == "full":
     75         #     comps = format_full(df)

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in format_basic(df, cfg)
    103     setattr(getattr(cfg, "plot"), "report", True)
    104     if cfg.missingvalues.enable:
--> 105         data, completions = basic_computations(df, cfg)
    106     else:
    107         data = basic_computations(df, cfg)

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in basic_computations(df, cfg)
    281                 data[col] = nom_comps(srs, srs.head(), cfg)
    282             elif isinstance(dtype, Nominal):
--> 283                 data[col] = nom_comps(df.frame[col], head[col], cfg)
    284             elif isinstance(dtype, SmallCardNum):
    285                 srs = df.get_col_as_str(col, na_as_str=False)

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/distribution/compute/univariate.py in nom_comps(srs, head, cfg)
    143 
    144     if cfg.stats.enable or cfg.wordlen.enable:
--> 145         if not head.apply(lambda x: isinstance(x, str)).all():
    146             srs = srs.astype(str)  # srs must be a string to compute the value lengths
    147     if cfg.stats.enable or cfg.wordcloud.enable or cfg.wordfreq.enable:

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/generic.py in logical_func(self, axis, bool_only, skipna, level, **kwargs)
  11363 
  11364     # ----------------------------------------------------------------------
> 11365     # Misc methods
  11366 
  11367     @final

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/series.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
   3870         --------
   3871         >>> s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
-> 3872         >>> s
   3873         0      cat
   3874         1      dog

~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/arrays/categorical.py in _reduce(self, name, axis, **kwargs)
   2122         cls: Type[CategoricalT], to_concat: Sequence[CategoricalT], axis: int = 0
   2123     ) -> CategoricalT:
-> 2124         from pandas.core.dtypes.concat import union_categoricals
   2125 
   2126         return union_categoricals(to_concat)

TypeError: Categorical cannot perform the operation all
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome/Pycharm
 - Platform Jupyter Notebook
 - Platform Version 
      jupyter==1.0.0
      jupyter-client==6.1.11
      jupyter-console==6.2.0
      jupyter-core==4.7.0
      jupyter-dash==0.4.0
      jupyterlab-pygments==0.1.2
      jupyterlab-widgets==1.0.0

 - Python Version 3.7.9
 - Dataprep Version  dataprep-0.3.0

To reproduce, sort of, giving a slightly different error:

        #%%
        import pandas as pd
        from datetime import datetime
        from dataprep.eda import create_report
        from dataprep.eda import plot_missing
        from dataprep.tests.eda.random_data_generator import gen_test_df
        df = gen_test_df()
        #df['month'] = pd.Categorical(datetime.now().strftime('%Y/%m %b')) #ValueError: Length of values (1) does not match length of index (30)
        df['month'] = datetime.now().strftime('%Y/%m %b')
        df['month'] = df.month.astype('category')
        df.info()
        
        #%%
        create_report(df)

Error is now:

TypeError: 'Categorical' does not implement reduction 'all'

        
        ---------------------------------------------------------------------------
        
        TypeError                                 Traceback (most recent call last)
        
        <ipython-input-15-463fb2fdfb17> in <module>
        ----> 1 create_report(df)
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/__init__.py in create_report(df, config, display, title, mode, progress)
             66         "resources": INLINE.render(),
             67         "title": title,
        ---> 68         "components": format_report(df, cfg, mode, progress),
             69     }
             70     template_base = ENV_LOADER.get_template("base.html")
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in format_report(df, cfg, mode, progress)
             71         if mode == "basic":
             72             edaframe = EDAFrame(df)
        ---> 73             comps = format_basic(edaframe, cfg)
             74         # elif mode == "full":
             75         #     comps = format_full(df)
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in format_basic(df, cfg)
            103     setattr(getattr(cfg, "plot"), "report", True)
            104     if cfg.missingvalues.enable:
        --> 105         data, completions = basic_computations(df, cfg)
            106     else:
            107         data = basic_computations(df, cfg)
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/create_report/formatter.py in basic_computations(df, cfg)
            281                 data[col] = nom_comps(srs, srs.head(), cfg)
            282             elif isinstance(dtype, Nominal):
        --> 283                 data[col] = nom_comps(df.frame[col], head[col], cfg)
            284             elif isinstance(dtype, SmallCardNum):
            285                 srs = df.get_col_as_str(col, na_as_str=False)
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/dataprep/eda/distribution/compute/univariate.py in nom_comps(srs, head, cfg)
            143 
            144     if cfg.stats.enable or cfg.wordlen.enable:
        --> 145         if not head.apply(lambda x: isinstance(x, str)).all():
            146             srs = srs.astype(str)  # srs must be a string to compute the value lengths
            147     if cfg.stats.enable or cfg.wordcloud.enable or cfg.wordfreq.enable:
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/generic.py in all(self, axis, bool_only, skipna, level, **kwargs)
          10884         )
          10885         def all(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs):
        > 10886             return NDFrame.all(self, axis, bool_only, skipna, level, **kwargs)
          10887 
          10888         # pandas\core\generic.py:10719: error: Cannot assign to a method
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/generic.py in all(self, axis, bool_only, skipna, level, **kwargs)
          10598     def all(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs):
          10599         return self._logical_func(
        > 10600             "all", nanops.nanall, axis, bool_only, skipna, level, **kwargs
          10601         )
          10602 
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/generic.py in _logical_func(self, name, func, axis, bool_only, skipna, level, **kwargs)
          10588             skipna=skipna,
          10589             numeric_only=bool_only,
        > 10590             filter_type="bool",
          10591         )
          10592 
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/series.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
           4171         if isinstance(delegate, ExtensionArray):
           4172             # dispatch to ExtensionArray interface
        -> 4173             return delegate._reduce(name, skipna=skipna, **kwds)
           4174 
           4175         else:
        
        ~/PycharmProjects/.venv/tinycloud379/lib/python3.7/site-packages/pandas/core/arrays/_mixins.py in _reduce(self, name, skipna, **kwargs)
            274         else:
            275             msg = f"'{type(self).__name__}' does not implement reduction '{name}'"
        --> 276             raise TypeError(msg)
            277 
            278     def _wrap_reduction_result(self, axis: Optional[int], result):
        
        TypeError: 'Categorical' does not implement reduction 'all'

**Comment by jinglinpeng** [comment]
Hi @phoebebright , Thanks for the bug report. It has been fixed by #650. You could try the latest version of `develop` branch with: `pip install -U git+https://github.com/sfu-db/dataprep.git@develop`
