### ISSUE TITLE
Interaction chart not generated using create_report()

### ISSUE THREAD

**Issue by vivek04jmi** [sfu-db/dataprep#652]
dataprep version - 0.2.11
Python version - 3.6.5
using jupyter notebook

on executing create_report(df) getting error - "Something Happened: singular matrix: resolution failed at diagonal 0" against Interactions plot. 
Other plots are getting generated using create_report(). Getting error only for Interactions
df taken here is from titanic train data set

Is there any way to solve this issue with the dataprep library version 0.2.11?

**Comment by vivek04jmi** [comment]
I am unable to upgrade library beyond the dataprep version 0.2.11.

**Comment by jinglinpeng** [comment]
@vivek04jmi  What's the error msg with your upgrade?

**Comment by vivek04jmi** [comment]
Getting below error message at the end
Failed with error code 1 in None
