### ISSUE TITLE
plot: error in x ticks for some dataset

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#66]
For some dataset, the x ticks of plot may have issues. Please try the following code:
`import pandas as pd`
`from dataprep.eda import *`
`df = pd.read_csv('https://www.openml.org/data/get_csv/52236/phpAyyBys', na_values = ['?', 'nan'])`
`plot(df)`
The result is as follows:
![Screen Shot 2020-01-30 at 4 14 34 PM](https://user-images.githubusercontent.com/18078770/73501724-a23a7580-437b-11ea-9c64-da73b0edb9e3.png)

**Comment by jinglinpeng** [comment]
Could you please take a look? @brandonlockhart

**Comment by brandonlockhart** [comment]
This is fixed 
![Screenshot at 2020-02-06 09:23:59](https://user-images.githubusercontent.com/25874021/73961992-7d398b80-48c2-11ea-95a2-1907e39ea187.png)
