### ISSUE TITLE
'import dataprep.eda' canot run in python 3.6.*

### ISSUE THREAD

**Issue by biand** [sfu-db/dataprep#678]
**Describe the bug**
pip install -U dataprep

import dataprep.eda

 File "/home/aaa/.virtualenvs/py3.6.9/lib/python3.6/site-packages/dataprep/eda/configs.py", line 20
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined

**Expected behavior**
Excuse me, How can I run Dataprep.eda in python 3.6.9 , or maybe install it from source?
0.1.0 0.2.* also show differente error in python 3.6.9.
Sincerely yours.

**Comment by dovahcrow** [comment]
Hi @biand , yes dataprep currently does not support python 3.6 anymore. Given that python 3.6 is reaching its eol (https://endoflife.date/python), I suggest you can update the python version to at least 3.7.
