### ISSUE TITLE
clean_phone not registering phone numbers with type 'numpy.float64'

### ISSUE THREAD

**Issue by AustinJamesWolff** [sfu-db/dataprep#682]
**Describe the bug**
clean_phone function appears to be working when the list of phone numbers in my dataframe (old_agile) that are of type "string," but in a different dataframe, it's not working correctly. The only difference is the dataframe it's not working on (old_highlevel), the list of phone numbers are of type "numpy.float64." Is this supposed to matter? There's no mention in the documentation of this mattering (at least not that I could find in the documentation of the clean_phone function). If I'm missing something, please let me know! I'm new to this and it's quite probable I'm overlooking something.

**To Reproduce**
1. Have a list of phone numbers, but with type "numpy.float64"
2. Try using the "clean_phone" function on it
3. The function may return a list of just NaN items

**Expected behavior**
For the clean_phone function to return my "highlevel_phone" data into "highlevel_phone_clean" exactly as it did with "agile_phone_clean" in the screenshots listed below.

**Screenshots**
Screenshots attached of the code/csv file which this is working correctly, and that which is not working correctly.
![NOT WORKING_old_highlevel](https://user-images.githubusercontent.com/85139314/131573946-a73aa7ba-bf33-44b2-9949-cc5d079220ff.png)
^ NOT WORKING

![WORKING_old_agile](https://user-images.githubusercontent.com/85139314/131573950-cb5e3412-81c8-4e2a-8228-86999bc57849.png)
^ WORKING CORRECTLY

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]
 - Platform [Google Colab]
 - Platform Version [92.0]
 - Python Version [3.7.2]
 - Dataprep Version [0.3]

**Comment by qidanrui** [comment]
We indeed transfer any type to the string type by default actually
However, when the type is numpy.float64, the phone number of 12336789000 becomes 12336789000.0
and after calling the str(12336789000.0), the output is '12336789000.0' and the string cannot be recognized as a phone.

**Comment by AustinJamesWolff** [comment]
> We indeed transfer any type to the string type by default actually
> However, when the type is numpy.float64, the phone number of 12336789000 becomes 12336789000.0
> and after calling the str(12336789000.0), the output is '12336789000.0' and the string cannot be recognized as a phone

Thank you very much!
