### ISSUE TITLE
exclude certain parts of Create_Report to make it more portable.

### ISSUE THREAD

**Issue by RakshithRAcharya** [sfu-db/dataprep#744]
**_Is your feature request related to a problem? Please describe._**
First of all great work here. When we do `create_report(df)` the report contains overview, variables, interactions, correlations and Missing value. This is super cool. But when there are too many numerical columns in the df the interactions take a bit longer time. So for those kind of report please give an option to exclude certain parts of the report so it completes faster.

**_Describe the solution you'd like_**
The solution I would like to suggest is that there be an option like `create_report(df, interactions=None)` so that the interaction is excluded from the report. and similarly for other parts of the report.

**_Alternate Solution_**
Alternate solution that I would suggest would be something like `create_summary_report(df)` where the report only adds overview and variables to the report

Still thank you for this amazing library.

**Comment by jinglinpeng** [comment]
Hi @RakshithRAcharya , thanks for the issue. You could use the following config to disable interactions:
```python
create_report(df, config = {"interactions.enable": False})
```
Besides, if you only want to show some sections such as variables and disable all other sections, you can also set the `display` parameter as follows:
```python
create_report(df, display=["Variables"])
```

**Comment by RakshithRAcharya** [comment]
Great.....Can you give examples to all the configs??......Thank you

**Comment by jinglinpeng** [comment]
Hi @RakshithRAcharya , please check this doc for the available configs: https://github.com/sfu-db/dataprep/blob/develop/docs/source/user_guide/eda/parameter_configurations.ipynb.

**Comment by RakshithRAcharya** [comment]
Thank you for your time........I'll close this then
