### ISSUE TITLE
dataprep.eda: add case study for 'Titanic'

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#75]
The task is to add a case study (on jupyter notebook) of using dataprep.eda to do ML task.

**Comment by dovahcrow** [comment]
The case study has 2 purposes:
1. Help us figure out if the current API design is complete and easy to use.
2. Educate the users on how to use our tool to finish popular tasks.

TODO:
- [ ] Create Jupyter Notebook.
- [ ] Add the use case into the documentation.

**Comment by jinglinpeng** [comment]
Jiannan suggests add another case study to show the efficiency of large data. Will submit a new issue and do it after the above two cases finished.

**Comment by jinglinpeng** [comment]
I create a new issue for housing price case study. @Waterpine
