### ISSUE TITLE
No module named 'dataprep.eda'; 'dataprep' is not a package

### ISSUE THREAD

**Issue by bayuaji732** [sfu-db/dataprep#767]
**Describe the bug**
while I try to import dataprep.eda from python in terminal it show error. but while I running it at jupyter notebook its running fine. 

**To Reproduce**
1. add from dataprep.eda import create_report
2. running the python script from terminal
3. See error

**Expected behavior**
running well at terminal or python script

**Screenshots**
![image](https://user-images.githubusercontent.com/34885485/145013381-d1958f3d-c959-454f-8fa0-31c833e9c2f7.png)

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Platform [Jupyter Notebook, Python script, anaconda]
 - Python Version [3.7.11]
 - Dataprep Version [0.4.1]

**Additional context**
Any idea how to solve this error? thanks

**Comment by rloredo** [comment]
Same for me, but it doesn't work in JN.

OS: MacOS Monterey 12.1 - M1 chipset
Platform [Jupyter Notebook,  pyenv]
Python version [3.9.9]

**Additional context**
when using a script or python in the terminal I get this warning: 

UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv. 

But I have IPython installed inside and any other package works ok.

**Comment by jinglinpeng** [comment]
Hi @bayuaji732 , is it due to naming conflict issue? https://stackoverflow.com/questions/54333865/python-no-module-named-error-package-is-not-a-package

**Comment by jinglinpeng** [comment]
Hi @rloredo , is the error happened in terminal or notebook? It would be nice if you could paste the error info.

**Comment by bayuaji732** [comment]
@jinglinpeng yeah, I found the problem. I installed anaconda at user but I try running the python above from root, so it can't find the python package.

so issue closed. I think.

thanks
