### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by jefwang9** [sfu-db/dataprep#778]
**Describe the bug**
After installing dataprep, when I ran the code like this:
from dataprep.eda import plot
import pandas as pd

df = pd.read_csv("faculty_table.csv")
plot(df)

It shows:
Javascript error adding output!
ReferenceError: Can't find variable: Bokeh
See your browser Javascript console for more details.

**To Reproduce**

Or:

```python
paste your code here
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Platform [Jupyter Notebook, Jupyter Lab, Google Colab, VSCode, Python script]
 - Platform Version [e.g. 1.0]
 - Python Version [e.g. 3.7.2]
 - Dataprep Version [e.g. 0.2.2]

**Additional context**

**Comment by jinglinpeng** [comment]
Hi @jefwang9 , it seems the error happened in Bokeh. Could you provide more information so I can reproduce the error? E.g., the dataset, the OS, the platform, dataprep version and a screenshot of the error.

**Comment by jefwang9** [comment]
Issue fixed after changing the version of pandas. Thanks.

**Comment by dovahcrow** [comment]
Hi @jefwang9 may I ask if you can post the working pandas version here? This might help other users with the same issue.
