### ISSUE TITLE
SSLCertVerificationError with dataprep.connector but not requests module?

### ISSUE THREAD

**Issue by brendanartley** [sfu-db/dataprep#788]
**Describe the bug**

I am trying to use the dataprep.connector with the NHL API that does not required API Keys. 

[NHL_API Documentation](https://gitlab.com/dword4/nhlapi)

I am get a response with no errors when I use the requests module like in the following code block.

```
import requests

r = requests.get("https://records.nhl.com/site/api/attendance")
r.json()
```
Yet when I try and do the same with the dataprep.connector, I am getting a SSLCertVerificationError and a ClientConnectorCertificateError. 
```
conn = Connector(config_path="./config")
attendance = await conn.query("attendance")
```
```
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

ClientConnectorCertificateError: Cannot connect to host records.nhl.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
```
My config file is very simple and looks like the following.
```
{
    "version": 1,
    "request": {
        "url": "http://records.nhl.com/site/api/attendance",
        "method": "GET",
        "params": {
            "cayenneExp": false
        }
    },
    "response": {
        "ctype": "application/json",
        "tablePath": "$.data[*]",
        "schema": {
            "Id": {
                "target": "$.id",
                "type": "int"
            },
            "seasonId": {
                "target": "$.seasonId",
                "type": "int"
            },
            "playoffAttendance": {
                "target": "$.playoffAttendance",
                "type": "int"
            },
            "regularAttendance": {
                "target": "$.regularAttendance",
                "type": "int"
            },
            "totalAttendance": {
                "target": "$.totalAttendance",
                "type": "int"
            }
        },
        "orient": "records"
    }
}
```
I dont see why this would work without errors with the requests module and not with the dataprep.connector? If anyone knows why this was the case let me know!

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.6
 - Browser: Chrome
 - Platform: Jupyter Notebook / Python script
 - Python Version: 3.8.3
 - Dataprep Version:  0.4.1

**Additional context**

I have tried the following to fix the error so far.

1. Making sure I am using the most up to date certifi version
`pip install certifi --upgrade`

2. Attempting the API call with both http and https

**Comment by dovahcrow** [comment]
Connector is using aiohttp instead of requests so I think this might be the issue although I cannot reproduce the issue on my side..

**Comment by dovahcrow** [comment]
Are you using Windows? It looks like the issue might have a similar cause to this one https://github.com/Rapptz/discord.py/issues/4159.

**Comment by brendanartley** [comment]
@Rapptz's solution worked. Thank you!
