### ISSUE TITLE
Plot() result is not visible on VSCode.

### ISSUE THREAD

**Issue by AllyHyeseongKim** [sfu-db/dataprep#896]
**Describe the bug**
https://github.com/sfu-db/dataprep/blob/4309f768710cb88ddd851deb2e6be0bba56512c4/dataprep/eda/create_diff_report/templates/styles.html#L16-L23
When we use `VSCode`, due to the setting of the `width` and `justify-content: center` of the `.vp-plot`, the right side of the picture is not visible. 

**To Reproduce**
```python
`dataprep.eda.plot({dataframe})`
```

**Screenshots**
<img width="1442" alt="스크린샷 2022-05-11 오후 3 38 29" src="https://user-images.githubusercontent.com/39588623/167784931-53927519-9160-4f85-9da9-5383c16ce3cd.png">

**Desktop (please complete the following information):**
 - OS: `MacOS Monterey (12.3.1)`
 - Browser `chrome`
 - Platform `VSCode`
 - Platform Version `1.67.1 (Universal)`
 - Python Version `3.8.13`
 - Dataprep Version `0.4.3a1`

with @yesulpark, @spear011

**Comment by yesulpark** [comment]
**Describe the bug**

Windows also have the same problem at vsc.
Additionally both environment use jupyter notebook(.ipynb) file in vsc.

**Screenshots**
![image](https://user-images.githubusercontent.com/78015166/167966715-62da9c11-6bdf-4297-8271-9c400830d454.png)

**Desktop**
OS: Microsoft Windows 11 Home(version 10.0.22000/build 22000)
Browser chrome
Platform VSCode
Platform Version 1.67.1 (Universal)
Python Version 3.8.13
Dataprep Version 0.4.3a1

**Comment by AllyHyeseongKim** [comment]
It seems that the center alignment of the `.vp-plot` causes the problem.

**Comment by osbm** [comment]
Yes, i am using VSCode on Kubuntu and also this happens.
