### ISSUE TITLE
data_connector: issue using API parameters without template variables

### ISSUE THREAD

**Issue by pallavibharadwaj** [sfu-db/dataprep#92]
Support for templates was added in [this](https://github.com/sfu-db/dataprep/pull/70) PR.
When template variables are not specified in the API request, the template value still contains the string around it and is not "empty". This always results in `key conflicting with to_key` Warning and returns empty results.

Example: 
if `first_name` and `last_name` are template variables and are not mentioned in the request and `to_key` is `q` and is specified in the following manner:
`df = dc.query("publication", q="Journal Articles")`
The request contains template value `<Template memory:7f4f6c36c2d0> author:_:` with the above Warning. Instead of returning the publications of type "Journal Articles", it would return an empty data frame.

**Comment by dovahcrow** [comment]
Hi I think this issue is fixed by commit f543c68.
